/* File: _stlmodule.c
 * This file is auto-generated with f2py (version:2).
 * f2py is a Fortran to Python Interface Generator (FPIG), Second Edition,
 * written by Pearu Peterson <pearu@cens.ioc.ee>.
 * Generation date: Tue Oct 27 18:02:38 2020
 * Do not edit this file directly unless you know what you are doing!!!
 */

#ifdef __cplusplus
extern "C" {
#endif

/*********************** See f2py2e/cfuncs.py: includes ***********************/
#include "Python.h"
#include <stdarg.h>
#include "fortranobject.h"
#include <math.h>

/**************** See f2py2e/rules.py: mod_rules['modulebody'] ****************/
static PyObject *_stl_error;
static PyObject *_stl_module;

/*********************** See f2py2e/cfuncs.py: typedefs ***********************/
/*need_typedefs*/

/****************** See f2py2e/cfuncs.py: typedefs_generated ******************/
/*need_typedefs_generated*/

/********************** See f2py2e/cfuncs.py: cppmacros **********************/
#if defined(PREPEND_FORTRAN)
#if defined(NO_APPEND_FORTRAN)
#if defined(UPPERCASE_FORTRAN)
#define F_FUNC(f,F) _##F
#else
#define F_FUNC(f,F) _##f
#endif
#else
#if defined(UPPERCASE_FORTRAN)
#define F_FUNC(f,F) _##F##_
#else
#define F_FUNC(f,F) _##f##_
#endif
#endif
#else
#if defined(NO_APPEND_FORTRAN)
#if defined(UPPERCASE_FORTRAN)
#define F_FUNC(f,F) F
#else
#define F_FUNC(f,F) f
#endif
#else
#if defined(UPPERCASE_FORTRAN)
#define F_FUNC(f,F) F##_
#else
#define F_FUNC(f,F) f##_
#endif
#endif
#endif
#if defined(UNDERSCORE_G77)
#define F_FUNC_US(f,F) F_FUNC(f##_,F##_)
#else
#define F_FUNC_US(f,F) F_FUNC(f,F)
#endif

#define rank(var) var ## _Rank
#define shape(var,dim) var ## _Dims[dim]
#define old_rank(var) (PyArray_NDIM((PyArrayObject *)(capi_ ## var ## _tmp)))
#define old_shape(var,dim) PyArray_DIM(((PyArrayObject *)(capi_ ## var ## _tmp)),dim)
#define fshape(var,dim) shape(var,rank(var)-dim-1)
#define len(var) shape(var,0)
#define flen(var) fshape(var,0)
#define old_size(var) PyArray_SIZE((PyArrayObject *)(capi_ ## var ## _tmp))
/* #define index(i) capi_i ## i */
#define slen(var) capi_ ## var ## _len
#define size(var, ...) f2py_size((PyArrayObject *)(capi_ ## var ## _tmp), ## __VA_ARGS__, -1)

#define CHECKSCALAR(check,tcheck,name,show,var)\
    if (!(check)) {\
        char errstring[256];\
        sprintf(errstring, "%s: "show, "("tcheck") failed for "name, var);\
        PyErr_SetString(_stl_error,errstring);\
        /*goto capi_fail;*/\
    } else 
#ifdef DEBUGCFUNCS
#define CFUNCSMESS(mess) fprintf(stderr,"debug-capi:"mess);
#define CFUNCSMESSPY(mess,obj) CFUNCSMESS(mess) \
    PyObject_Print((PyObject *)obj,stderr,Py_PRINT_RAW);\
    fprintf(stderr,"\n");
#else
#define CFUNCSMESS(mess)
#define CFUNCSMESSPY(mess,obj)
#endif

#ifndef max
#define max(a,b) ((a > b) ? (a) : (b))
#endif
#ifndef min
#define min(a,b) ((a < b) ? (a) : (b))
#endif
#ifndef MAX
#define MAX(a,b) ((a > b) ? (a) : (b))
#endif
#ifndef MIN
#define MIN(a,b) ((a < b) ? (a) : (b))
#endif


/************************ See f2py2e/cfuncs.py: cfuncs ************************/
static int f2py_size(PyArrayObject* var, ...)
{
  npy_int sz = 0;
  npy_int dim;
  npy_int rank;
  va_list argp;
  va_start(argp, var);
  dim = va_arg(argp, npy_int);
  if (dim==-1)
    {
      sz = PyArray_SIZE(var);
    }
  else
    {
      rank = PyArray_NDIM(var);
      if (dim>=1 && dim<=rank)
        sz = PyArray_DIM(var, dim-1);
      else
        fprintf(stderr, "f2py_size: 2nd argument value=%d fails to satisfy 1<=value<=%d. Result will be 0.\n", dim, rank);
    }
  va_end(argp);
  return sz;
}

static int int_from_pyobj(int* v,PyObject *obj,const char *errmess) {
    PyObject* tmp = NULL;
    if (PyInt_Check(obj)) {
        *v = (int)PyInt_AS_LONG(obj);
        return 1;
    }
    tmp = PyNumber_Int(obj);
    if (tmp) {
        *v = PyInt_AS_LONG(tmp);
        Py_DECREF(tmp);
        return 1;
    }
    if (PyComplex_Check(obj))
        tmp = PyObject_GetAttrString(obj,"real");
    else if (PyString_Check(obj) || PyUnicode_Check(obj))
        /*pass*/;
    else if (PySequence_Check(obj))
        tmp = PySequence_GetItem(obj,0);
    if (tmp) {
        PyErr_Clear();
        if (int_from_pyobj(v,tmp,errmess)) {Py_DECREF(tmp); return 1;}
        Py_DECREF(tmp);
    }
    {
        PyObject* err = PyErr_Occurred();
        if (err==NULL) err = _stl_error;
        PyErr_SetString(err,errmess);
    }
    return 0;
}

static int double_from_pyobj(double* v,PyObject *obj,const char *errmess) {
    PyObject* tmp = NULL;
    if (PyFloat_Check(obj)) {
#ifdef __sgi
        *v = PyFloat_AsDouble(obj);
#else
        *v = PyFloat_AS_DOUBLE(obj);
#endif
        return 1;
    }
    tmp = PyNumber_Float(obj);
    if (tmp) {
#ifdef __sgi
        *v = PyFloat_AsDouble(tmp);
#else
        *v = PyFloat_AS_DOUBLE(tmp);
#endif
        Py_DECREF(tmp);
        return 1;
    }
    if (PyComplex_Check(obj))
        tmp = PyObject_GetAttrString(obj,"real");
    else if (PyString_Check(obj) || PyUnicode_Check(obj))
        /*pass*/;
    else if (PySequence_Check(obj))
        tmp = PySequence_GetItem(obj,0);
    if (tmp) {
        PyErr_Clear();
        if (double_from_pyobj(v,tmp,errmess)) {Py_DECREF(tmp); return 1;}
        Py_DECREF(tmp);
    }
    {
        PyObject* err = PyErr_Occurred();
        if (err==NULL) err = _stl_error;
        PyErr_SetString(err,errmess);
    }
    return 0;
}


/********************* See f2py2e/cfuncs.py: userincludes *********************/
/*need_userincludes*/

/********************* See f2py2e/capi_rules.py: usercode *********************/


/* See f2py2e/rules.py */
extern void F_FUNC(stl,STL)(double*,int*,int*,int*,int*,int*,int*,int*,int*,int*,int*,int*,int*,int*,double*,double*,double*,double*);
extern void F_FUNC(ess,ESS)(double*,int*,int*,int*,int*,int*,double*,double*,double*);
extern void F_FUNC(est,EST)(double*,int*,int*,int*,double*,double*,int*,int*,double*,int*,double*,int*);
extern void F_FUNC(fts,FTS)(double*,int*,int*,double*,double*);
extern void F_FUNC(ma,MA)(double*,int*,int*,double*);
extern void F_FUNC(onestp,ONESTP)(double*,int*,int*,int*,int*,int*,int*,int*,int*,int*,int*,int*,int*,int*,double*,double*,double*,double*);
extern void F_FUNC(rwts,RWTS)(double*,int*,double*,double*);
extern void F_FUNC(ss,SS)(double*,int*,int*,int*,int*,int*,int*,double*,double*,double*,double*,double*,double*);
extern void F_FUNC(stlez,STLEZ)(double*,int*,int*,int*,int*,int*,int*,int*,double*,double*,double*,double*);
extern void F_FUNC(psort,PSORT)(double*,int*,int*,int*);
/*eof externroutines*/

/******************** See f2py2e/capi_rules.py: usercode1 ********************/


/******************* See f2py2e/cb_rules.py: buildcallback *******************/
/*need_callbacks*/

/*********************** See f2py2e/rules.py: buildapi ***********************/

/************************************ stl ************************************/
static char doc_f2py_rout__stl_stl[] = "\
rw,season,trend,work = stl(y,np,ns,nt,nl,isdeg,itdeg,ildeg,nsjump,ntjump,nljump,ni,no,[n])\n\nWrapper for ``stl``.\
\n\nParameters\n----------\n"
"y : input rank-1 array('d') with bounds (n)\n"
"np : input int\n"
"ns : input int\n"
"nt : input int\n"
"nl : input int\n"
"isdeg : input int\n"
"itdeg : input int\n"
"ildeg : input int\n"
"nsjump : input int\n"
"ntjump : input int\n"
"nljump : input int\n"
"ni : input int\n"
"no : input int\n"
"\nOther Parameters\n----------------\n"
"n : input int, optional\n    Default: len(y)\n"
"\nReturns\n-------\n"
"rw : rank-1 array('d') with bounds (n)\n"
"season : rank-1 array('d') with bounds (n)\n"
"trend : rank-1 array('d') with bounds (n)\n"
"work : rank-2 array('d') with bounds (n+2*np,5)";
/* extern void F_FUNC(stl,STL)(double*,int*,int*,int*,int*,int*,int*,int*,int*,int*,int*,int*,int*,int*,double*,double*,double*,double*); */
static PyObject *f2py_rout__stl_stl(const PyObject *capi_self,
                           PyObject *capi_args,
                           PyObject *capi_keywds,
                           void (*f2py_func)(double*,int*,int*,int*,int*,int*,int*,int*,int*,int*,int*,int*,int*,int*,double*,double*,double*,double*)) {
  PyObject * volatile capi_buildvalue = NULL;
  volatile int f2py_success = 1;
/*decl*/

  double *y = NULL;
  npy_intp y_Dims[1] = {-1};
  const int y_Rank = 1;
  PyArrayObject *capi_y_tmp = NULL;
  int capi_y_intent = 0;
  PyObject *y_capi = Py_None;
  int n = 0;
  PyObject *n_capi = Py_None;
  int np = 0;
  PyObject *np_capi = Py_None;
  int ns = 0;
  PyObject *ns_capi = Py_None;
  int nt = 0;
  PyObject *nt_capi = Py_None;
  int nl = 0;
  PyObject *nl_capi = Py_None;
  int isdeg = 0;
  PyObject *isdeg_capi = Py_None;
  int itdeg = 0;
  PyObject *itdeg_capi = Py_None;
  int ildeg = 0;
  PyObject *ildeg_capi = Py_None;
  int nsjump = 0;
  PyObject *nsjump_capi = Py_None;
  int ntjump = 0;
  PyObject *ntjump_capi = Py_None;
  int nljump = 0;
  PyObject *nljump_capi = Py_None;
  int ni = 0;
  PyObject *ni_capi = Py_None;
  int no = 0;
  PyObject *no_capi = Py_None;
  double *rw = NULL;
  npy_intp rw_Dims[1] = {-1};
  const int rw_Rank = 1;
  PyArrayObject *capi_rw_tmp = NULL;
  int capi_rw_intent = 0;
  double *season = NULL;
  npy_intp season_Dims[1] = {-1};
  const int season_Rank = 1;
  PyArrayObject *capi_season_tmp = NULL;
  int capi_season_intent = 0;
  double *trend = NULL;
  npy_intp trend_Dims[1] = {-1};
  const int trend_Rank = 1;
  PyArrayObject *capi_trend_tmp = NULL;
  int capi_trend_intent = 0;
  double *work = NULL;
  npy_intp work_Dims[2] = {-1, -1};
  const int work_Rank = 2;
  PyArrayObject *capi_work_tmp = NULL;
  int capi_work_intent = 0;
  static char *capi_kwlist[] = {"y","np","ns","nt","nl","isdeg","itdeg","ildeg","nsjump","ntjump","nljump","ni","no","n",NULL};

/*routdebugenter*/
#ifdef F2PY_REPORT_ATEXIT
f2py_start_clock();
#endif
  if (!PyArg_ParseTupleAndKeywords(capi_args,capi_keywds,\
    "OOOOOOOOOOOOO|O:_stl.stl",\
    capi_kwlist,&y_capi,&np_capi,&ns_capi,&nt_capi,&nl_capi,&isdeg_capi,&itdeg_capi,&ildeg_capi,&nsjump_capi,&ntjump_capi,&nljump_capi,&ni_capi,&no_capi,&n_capi))
    return NULL;
/*frompyobj*/
  /* Processing variable y */
  ;
  capi_y_intent |= F2PY_INTENT_IN;
  capi_y_tmp = array_from_pyobj(NPY_DOUBLE,y_Dims,y_Rank,capi_y_intent,y_capi);
  if (capi_y_tmp == NULL) {
    if (!PyErr_Occurred())
      PyErr_SetString(_stl_error,"failed in converting 1st argument `y' of _stl.stl to C/Fortran array" );
  } else {
    y = (double *)(PyArray_DATA(capi_y_tmp));

  /* Processing variable np */
    f2py_success = int_from_pyobj(&np,np_capi,"_stl.stl() 2nd argument (np) can't be converted to int");
  if (f2py_success) {
  /* Processing variable ns */
    f2py_success = int_from_pyobj(&ns,ns_capi,"_stl.stl() 3rd argument (ns) can't be converted to int");
  if (f2py_success) {
  /* Processing variable nt */
    f2py_success = int_from_pyobj(&nt,nt_capi,"_stl.stl() 4th argument (nt) can't be converted to int");
  if (f2py_success) {
  /* Processing variable nl */
    f2py_success = int_from_pyobj(&nl,nl_capi,"_stl.stl() 5th argument (nl) can't be converted to int");
  if (f2py_success) {
  /* Processing variable isdeg */
    f2py_success = int_from_pyobj(&isdeg,isdeg_capi,"_stl.stl() 6th argument (isdeg) can't be converted to int");
  if (f2py_success) {
  /* Processing variable itdeg */
    f2py_success = int_from_pyobj(&itdeg,itdeg_capi,"_stl.stl() 7th argument (itdeg) can't be converted to int");
  if (f2py_success) {
  /* Processing variable ildeg */
    f2py_success = int_from_pyobj(&ildeg,ildeg_capi,"_stl.stl() 8th argument (ildeg) can't be converted to int");
  if (f2py_success) {
  /* Processing variable nsjump */
    f2py_success = int_from_pyobj(&nsjump,nsjump_capi,"_stl.stl() 9th argument (nsjump) can't be converted to int");
  if (f2py_success) {
  /* Processing variable ntjump */
    f2py_success = int_from_pyobj(&ntjump,ntjump_capi,"_stl.stl() 10th argument (ntjump) can't be converted to int");
  if (f2py_success) {
  /* Processing variable nljump */
    f2py_success = int_from_pyobj(&nljump,nljump_capi,"_stl.stl() 11st argument (nljump) can't be converted to int");
  if (f2py_success) {
  /* Processing variable ni */
    f2py_success = int_from_pyobj(&ni,ni_capi,"_stl.stl() 12nd argument (ni) can't be converted to int");
  if (f2py_success) {
  /* Processing variable no */
    f2py_success = int_from_pyobj(&no,no_capi,"_stl.stl() 13rd argument (no) can't be converted to int");
  if (f2py_success) {
  /* Processing variable n */
  if (n_capi == Py_None) n = len(y); else
    f2py_success = int_from_pyobj(&n,n_capi,"_stl.stl() 1st keyword (n) can't be converted to int");
  if (f2py_success) {
  CHECKSCALAR(len(y)>=n,"len(y)>=n","1st keyword n","stl:n=%d",n) {
  /* Processing variable rw */
  rw_Dims[0]=n;
  capi_rw_intent |= F2PY_INTENT_OUT|F2PY_INTENT_HIDE;
  capi_rw_tmp = array_from_pyobj(NPY_DOUBLE,rw_Dims,rw_Rank,capi_rw_intent,Py_None);
  if (capi_rw_tmp == NULL) {
    if (!PyErr_Occurred())
      PyErr_SetString(_stl_error,"failed in converting hidden `rw' of _stl.stl to C/Fortran array" );
  } else {
    rw = (double *)(PyArray_DATA(capi_rw_tmp));

  /* Processing variable season */
  season_Dims[0]=n;
  capi_season_intent |= F2PY_INTENT_OUT|F2PY_INTENT_HIDE;
  capi_season_tmp = array_from_pyobj(NPY_DOUBLE,season_Dims,season_Rank,capi_season_intent,Py_None);
  if (capi_season_tmp == NULL) {
    if (!PyErr_Occurred())
      PyErr_SetString(_stl_error,"failed in converting hidden `season' of _stl.stl to C/Fortran array" );
  } else {
    season = (double *)(PyArray_DATA(capi_season_tmp));

  /* Processing variable trend */
  trend_Dims[0]=n;
  capi_trend_intent |= F2PY_INTENT_OUT|F2PY_INTENT_HIDE;
  capi_trend_tmp = array_from_pyobj(NPY_DOUBLE,trend_Dims,trend_Rank,capi_trend_intent,Py_None);
  if (capi_trend_tmp == NULL) {
    if (!PyErr_Occurred())
      PyErr_SetString(_stl_error,"failed in converting hidden `trend' of _stl.stl to C/Fortran array" );
  } else {
    trend = (double *)(PyArray_DATA(capi_trend_tmp));

  /* Processing variable work */
  work_Dims[0]=n+2*np,work_Dims[1]=5;
  capi_work_intent |= F2PY_INTENT_OUT|F2PY_INTENT_HIDE;
  capi_work_tmp = array_from_pyobj(NPY_DOUBLE,work_Dims,work_Rank,capi_work_intent,Py_None);
  if (capi_work_tmp == NULL) {
    if (!PyErr_Occurred())
      PyErr_SetString(_stl_error,"failed in converting hidden `work' of _stl.stl to C/Fortran array" );
  } else {
    work = (double *)(PyArray_DATA(capi_work_tmp));

/*end of frompyobj*/
#ifdef F2PY_REPORT_ATEXIT
f2py_start_call_clock();
#endif
/*callfortranroutine*/
        (*f2py_func)(y,&n,&np,&ns,&nt,&nl,&isdeg,&itdeg,&ildeg,&nsjump,&ntjump,&nljump,&ni,&no,rw,season,trend,work);
if (PyErr_Occurred())
  f2py_success = 0;
#ifdef F2PY_REPORT_ATEXIT
f2py_stop_call_clock();
#endif
/*end of callfortranroutine*/
    if (f2py_success) {
/*pyobjfrom*/
/*end of pyobjfrom*/
    CFUNCSMESS("Building return value.\n");
    capi_buildvalue = Py_BuildValue("NNNN",capi_rw_tmp,capi_season_tmp,capi_trend_tmp,capi_work_tmp);
/*closepyobjfrom*/
/*end of closepyobjfrom*/
    } /*if (f2py_success) after callfortranroutine*/
/*cleanupfrompyobj*/
  }  /*if (capi_work_tmp == NULL) ... else of work*/
  /* End of cleaning variable work */
  }  /*if (capi_trend_tmp == NULL) ... else of trend*/
  /* End of cleaning variable trend */
  }  /*if (capi_season_tmp == NULL) ... else of season*/
  /* End of cleaning variable season */
  }  /*if (capi_rw_tmp == NULL) ... else of rw*/
  /* End of cleaning variable rw */
  } /*CHECKSCALAR(len(y)>=n)*/
  } /*if (f2py_success) of n*/
  /* End of cleaning variable n */
  } /*if (f2py_success) of no*/
  /* End of cleaning variable no */
  } /*if (f2py_success) of ni*/
  /* End of cleaning variable ni */
  } /*if (f2py_success) of nljump*/
  /* End of cleaning variable nljump */
  } /*if (f2py_success) of ntjump*/
  /* End of cleaning variable ntjump */
  } /*if (f2py_success) of nsjump*/
  /* End of cleaning variable nsjump */
  } /*if (f2py_success) of ildeg*/
  /* End of cleaning variable ildeg */
  } /*if (f2py_success) of itdeg*/
  /* End of cleaning variable itdeg */
  } /*if (f2py_success) of isdeg*/
  /* End of cleaning variable isdeg */
  } /*if (f2py_success) of nl*/
  /* End of cleaning variable nl */
  } /*if (f2py_success) of nt*/
  /* End of cleaning variable nt */
  } /*if (f2py_success) of ns*/
  /* End of cleaning variable ns */
  } /*if (f2py_success) of np*/
  /* End of cleaning variable np */
  if((PyObject *)capi_y_tmp!=y_capi) {
    Py_XDECREF(capi_y_tmp); }
  }  /*if (capi_y_tmp == NULL) ... else of y*/
  /* End of cleaning variable y */
/*end of cleanupfrompyobj*/
  if (capi_buildvalue == NULL) {
/*routdebugfailure*/
  } else {
/*routdebugleave*/
  }
  CFUNCSMESS("Freeing memory.\n");
/*freemem*/
#ifdef F2PY_REPORT_ATEXIT
f2py_stop_clock();
#endif
  return capi_buildvalue;
}
/********************************* end of stl *********************************/

/************************************ ess ************************************/
static char doc_f2py_rout__stl_ess[] = "\
ess(y,len_bn,ideg,njump,userw,rw,ys,res,[n])\n\nWrapper for ``ess``.\
\n\nParameters\n----------\n"
"y : input rank-1 array('d') with bounds (n)\n"
"len_bn : input int\n"
"ideg : input int\n"
"njump : input int\n"
"userw : input int\n"
"rw : input rank-1 array('d') with bounds (n)\n"
"ys : input rank-1 array('d') with bounds (n)\n"
"res : input rank-1 array('d') with bounds (n)\n"
"\nOther Parameters\n----------------\n"
"n : input int, optional\n    Default: len(y)";
/* extern void F_FUNC(ess,ESS)(double*,int*,int*,int*,int*,int*,double*,double*,double*); */
static PyObject *f2py_rout__stl_ess(const PyObject *capi_self,
                           PyObject *capi_args,
                           PyObject *capi_keywds,
                           void (*f2py_func)(double*,int*,int*,int*,int*,int*,double*,double*,double*)) {
  PyObject * volatile capi_buildvalue = NULL;
  volatile int f2py_success = 1;
/*decl*/

  double *y = NULL;
  npy_intp y_Dims[1] = {-1};
  const int y_Rank = 1;
  PyArrayObject *capi_y_tmp = NULL;
  int capi_y_intent = 0;
  PyObject *y_capi = Py_None;
  int n = 0;
  PyObject *n_capi = Py_None;
  int len_bn = 0;
  PyObject *len_bn_capi = Py_None;
  int ideg = 0;
  PyObject *ideg_capi = Py_None;
  int njump = 0;
  PyObject *njump_capi = Py_None;
  int userw = 0;
  PyObject *userw_capi = Py_None;
  double *rw = NULL;
  npy_intp rw_Dims[1] = {-1};
  const int rw_Rank = 1;
  PyArrayObject *capi_rw_tmp = NULL;
  int capi_rw_intent = 0;
  PyObject *rw_capi = Py_None;
  double *ys = NULL;
  npy_intp ys_Dims[1] = {-1};
  const int ys_Rank = 1;
  PyArrayObject *capi_ys_tmp = NULL;
  int capi_ys_intent = 0;
  PyObject *ys_capi = Py_None;
  double *res = NULL;
  npy_intp res_Dims[1] = {-1};
  const int res_Rank = 1;
  PyArrayObject *capi_res_tmp = NULL;
  int capi_res_intent = 0;
  PyObject *res_capi = Py_None;
  static char *capi_kwlist[] = {"y","len_bn","ideg","njump","userw","rw","ys","res","n",NULL};

/*routdebugenter*/
#ifdef F2PY_REPORT_ATEXIT
f2py_start_clock();
#endif
  if (!PyArg_ParseTupleAndKeywords(capi_args,capi_keywds,\
    "OOOOOOOO|O:_stl.ess",\
    capi_kwlist,&y_capi,&len_bn_capi,&ideg_capi,&njump_capi,&userw_capi,&rw_capi,&ys_capi,&res_capi,&n_capi))
    return NULL;
/*frompyobj*/
  /* Processing variable y */
  ;
  capi_y_intent |= F2PY_INTENT_IN;
  capi_y_tmp = array_from_pyobj(NPY_DOUBLE,y_Dims,y_Rank,capi_y_intent,y_capi);
  if (capi_y_tmp == NULL) {
    if (!PyErr_Occurred())
      PyErr_SetString(_stl_error,"failed in converting 1st argument `y' of _stl.ess to C/Fortran array" );
  } else {
    y = (double *)(PyArray_DATA(capi_y_tmp));

  /* Processing variable len_bn */
    f2py_success = int_from_pyobj(&len_bn,len_bn_capi,"_stl.ess() 2nd argument (len_bn) can't be converted to int");
  if (f2py_success) {
  /* Processing variable ideg */
    f2py_success = int_from_pyobj(&ideg,ideg_capi,"_stl.ess() 3rd argument (ideg) can't be converted to int");
  if (f2py_success) {
  /* Processing variable njump */
    f2py_success = int_from_pyobj(&njump,njump_capi,"_stl.ess() 4th argument (njump) can't be converted to int");
  if (f2py_success) {
  /* Processing variable userw */
    userw = (int)PyObject_IsTrue(userw_capi);
    f2py_success = 1;
  if (f2py_success) {
  /* Processing variable n */
  if (n_capi == Py_None) n = len(y); else
    f2py_success = int_from_pyobj(&n,n_capi,"_stl.ess() 1st keyword (n) can't be converted to int");
  if (f2py_success) {
  CHECKSCALAR(len(y)>=n,"len(y)>=n","1st keyword n","ess:n=%d",n) {
  /* Processing variable rw */
  rw_Dims[0]=n;
  capi_rw_intent |= F2PY_INTENT_IN;
  capi_rw_tmp = array_from_pyobj(NPY_DOUBLE,rw_Dims,rw_Rank,capi_rw_intent,rw_capi);
  if (capi_rw_tmp == NULL) {
    if (!PyErr_Occurred())
      PyErr_SetString(_stl_error,"failed in converting 6th argument `rw' of _stl.ess to C/Fortran array" );
  } else {
    rw = (double *)(PyArray_DATA(capi_rw_tmp));

  /* Processing variable ys */
  ys_Dims[0]=n;
  capi_ys_intent |= F2PY_INTENT_IN;
  capi_ys_tmp = array_from_pyobj(NPY_DOUBLE,ys_Dims,ys_Rank,capi_ys_intent,ys_capi);
  if (capi_ys_tmp == NULL) {
    if (!PyErr_Occurred())
      PyErr_SetString(_stl_error,"failed in converting 7th argument `ys' of _stl.ess to C/Fortran array" );
  } else {
    ys = (double *)(PyArray_DATA(capi_ys_tmp));

  /* Processing variable res */
  res_Dims[0]=n;
  capi_res_intent |= F2PY_INTENT_IN;
  capi_res_tmp = array_from_pyobj(NPY_DOUBLE,res_Dims,res_Rank,capi_res_intent,res_capi);
  if (capi_res_tmp == NULL) {
    if (!PyErr_Occurred())
      PyErr_SetString(_stl_error,"failed in converting 8th argument `res' of _stl.ess to C/Fortran array" );
  } else {
    res = (double *)(PyArray_DATA(capi_res_tmp));

/*end of frompyobj*/
#ifdef F2PY_REPORT_ATEXIT
f2py_start_call_clock();
#endif
/*callfortranroutine*/
        (*f2py_func)(y,&n,&len_bn,&ideg,&njump,&userw,rw,ys,res);
if (PyErr_Occurred())
  f2py_success = 0;
#ifdef F2PY_REPORT_ATEXIT
f2py_stop_call_clock();
#endif
/*end of callfortranroutine*/
    if (f2py_success) {
/*pyobjfrom*/
/*end of pyobjfrom*/
    CFUNCSMESS("Building return value.\n");
    capi_buildvalue = Py_BuildValue("");
/*closepyobjfrom*/
/*end of closepyobjfrom*/
    } /*if (f2py_success) after callfortranroutine*/
/*cleanupfrompyobj*/
  if((PyObject *)capi_res_tmp!=res_capi) {
    Py_XDECREF(capi_res_tmp); }
  }  /*if (capi_res_tmp == NULL) ... else of res*/
  /* End of cleaning variable res */
  if((PyObject *)capi_ys_tmp!=ys_capi) {
    Py_XDECREF(capi_ys_tmp); }
  }  /*if (capi_ys_tmp == NULL) ... else of ys*/
  /* End of cleaning variable ys */
  if((PyObject *)capi_rw_tmp!=rw_capi) {
    Py_XDECREF(capi_rw_tmp); }
  }  /*if (capi_rw_tmp == NULL) ... else of rw*/
  /* End of cleaning variable rw */
  } /*CHECKSCALAR(len(y)>=n)*/
  } /*if (f2py_success) of n*/
  /* End of cleaning variable n */
  } /*if (f2py_success) of userw*/
  /* End of cleaning variable userw */
  } /*if (f2py_success) of njump*/
  /* End of cleaning variable njump */
  } /*if (f2py_success) of ideg*/
  /* End of cleaning variable ideg */
  } /*if (f2py_success) of len_bn*/
  /* End of cleaning variable len_bn */
  if((PyObject *)capi_y_tmp!=y_capi) {
    Py_XDECREF(capi_y_tmp); }
  }  /*if (capi_y_tmp == NULL) ... else of y*/
  /* End of cleaning variable y */
/*end of cleanupfrompyobj*/
  if (capi_buildvalue == NULL) {
/*routdebugfailure*/
  } else {
/*routdebugleave*/
  }
  CFUNCSMESS("Freeing memory.\n");
/*freemem*/
#ifdef F2PY_REPORT_ATEXIT
f2py_stop_clock();
#endif
  return capi_buildvalue;
}
/********************************* end of ess *********************************/

/************************************ est ************************************/
static char doc_f2py_rout__stl_est[] = "\
est(y,len_bn,ideg,xs,ys,nleft,nright,w,userw,rw,ok,[n])\n\nWrapper for ``est``.\
\n\nParameters\n----------\n"
"y : input rank-1 array('d') with bounds (n)\n"
"len_bn : input int\n"
"ideg : input int\n"
"xs : input float\n"
"ys : input float\n"
"nleft : input int\n"
"nright : input int\n"
"w : input rank-1 array('d') with bounds (n)\n"
"userw : input int\n"
"rw : input rank-1 array('d') with bounds (n)\n"
"ok : input int\n"
"\nOther Parameters\n----------------\n"
"n : input int, optional\n    Default: len(y)";
/* extern void F_FUNC(est,EST)(double*,int*,int*,int*,double*,double*,int*,int*,double*,int*,double*,int*); */
static PyObject *f2py_rout__stl_est(const PyObject *capi_self,
                           PyObject *capi_args,
                           PyObject *capi_keywds,
                           void (*f2py_func)(double*,int*,int*,int*,double*,double*,int*,int*,double*,int*,double*,int*)) {
  PyObject * volatile capi_buildvalue = NULL;
  volatile int f2py_success = 1;
/*decl*/

  double *y = NULL;
  npy_intp y_Dims[1] = {-1};
  const int y_Rank = 1;
  PyArrayObject *capi_y_tmp = NULL;
  int capi_y_intent = 0;
  PyObject *y_capi = Py_None;
  int n = 0;
  PyObject *n_capi = Py_None;
  int len_bn = 0;
  PyObject *len_bn_capi = Py_None;
  int ideg = 0;
  PyObject *ideg_capi = Py_None;
  double xs = 0;
  PyObject *xs_capi = Py_None;
  double ys = 0;
  PyObject *ys_capi = Py_None;
  int nleft = 0;
  PyObject *nleft_capi = Py_None;
  int nright = 0;
  PyObject *nright_capi = Py_None;
  double *w = NULL;
  npy_intp w_Dims[1] = {-1};
  const int w_Rank = 1;
  PyArrayObject *capi_w_tmp = NULL;
  int capi_w_intent = 0;
  PyObject *w_capi = Py_None;
  int userw = 0;
  PyObject *userw_capi = Py_None;
  double *rw = NULL;
  npy_intp rw_Dims[1] = {-1};
  const int rw_Rank = 1;
  PyArrayObject *capi_rw_tmp = NULL;
  int capi_rw_intent = 0;
  PyObject *rw_capi = Py_None;
  int ok = 0;
  PyObject *ok_capi = Py_None;
  static char *capi_kwlist[] = {"y","len_bn","ideg","xs","ys","nleft","nright","w","userw","rw","ok","n",NULL};

/*routdebugenter*/
#ifdef F2PY_REPORT_ATEXIT
f2py_start_clock();
#endif
  if (!PyArg_ParseTupleAndKeywords(capi_args,capi_keywds,\
    "OOOOOOOOOOO|O:_stl.est",\
    capi_kwlist,&y_capi,&len_bn_capi,&ideg_capi,&xs_capi,&ys_capi,&nleft_capi,&nright_capi,&w_capi,&userw_capi,&rw_capi,&ok_capi,&n_capi))
    return NULL;
/*frompyobj*/
  /* Processing variable y */
  ;
  capi_y_intent |= F2PY_INTENT_IN;
  capi_y_tmp = array_from_pyobj(NPY_DOUBLE,y_Dims,y_Rank,capi_y_intent,y_capi);
  if (capi_y_tmp == NULL) {
    if (!PyErr_Occurred())
      PyErr_SetString(_stl_error,"failed in converting 1st argument `y' of _stl.est to C/Fortran array" );
  } else {
    y = (double *)(PyArray_DATA(capi_y_tmp));

  /* Processing variable len_bn */
    f2py_success = int_from_pyobj(&len_bn,len_bn_capi,"_stl.est() 2nd argument (len_bn) can't be converted to int");
  if (f2py_success) {
  /* Processing variable ideg */
    f2py_success = int_from_pyobj(&ideg,ideg_capi,"_stl.est() 3rd argument (ideg) can't be converted to int");
  if (f2py_success) {
  /* Processing variable xs */
    f2py_success = double_from_pyobj(&xs,xs_capi,"_stl.est() 4th argument (xs) can't be converted to double");
  if (f2py_success) {
  /* Processing variable ys */
    f2py_success = double_from_pyobj(&ys,ys_capi,"_stl.est() 5th argument (ys) can't be converted to double");
  if (f2py_success) {
  /* Processing variable nleft */
    f2py_success = int_from_pyobj(&nleft,nleft_capi,"_stl.est() 6th argument (nleft) can't be converted to int");
  if (f2py_success) {
  /* Processing variable nright */
    f2py_success = int_from_pyobj(&nright,nright_capi,"_stl.est() 7th argument (nright) can't be converted to int");
  if (f2py_success) {
  /* Processing variable userw */
    userw = (int)PyObject_IsTrue(userw_capi);
    f2py_success = 1;
  if (f2py_success) {
  /* Processing variable ok */
    ok = (int)PyObject_IsTrue(ok_capi);
    f2py_success = 1;
  if (f2py_success) {
  /* Processing variable n */
  if (n_capi == Py_None) n = len(y); else
    f2py_success = int_from_pyobj(&n,n_capi,"_stl.est() 1st keyword (n) can't be converted to int");
  if (f2py_success) {
  CHECKSCALAR(len(y)>=n,"len(y)>=n","1st keyword n","est:n=%d",n) {
  /* Processing variable w */
  w_Dims[0]=n;
  capi_w_intent |= F2PY_INTENT_IN;
  capi_w_tmp = array_from_pyobj(NPY_DOUBLE,w_Dims,w_Rank,capi_w_intent,w_capi);
  if (capi_w_tmp == NULL) {
    if (!PyErr_Occurred())
      PyErr_SetString(_stl_error,"failed in converting 8th argument `w' of _stl.est to C/Fortran array" );
  } else {
    w = (double *)(PyArray_DATA(capi_w_tmp));

  /* Processing variable rw */
  rw_Dims[0]=n;
  capi_rw_intent |= F2PY_INTENT_IN;
  capi_rw_tmp = array_from_pyobj(NPY_DOUBLE,rw_Dims,rw_Rank,capi_rw_intent,rw_capi);
  if (capi_rw_tmp == NULL) {
    if (!PyErr_Occurred())
      PyErr_SetString(_stl_error,"failed in converting 10th argument `rw' of _stl.est to C/Fortran array" );
  } else {
    rw = (double *)(PyArray_DATA(capi_rw_tmp));

/*end of frompyobj*/
#ifdef F2PY_REPORT_ATEXIT
f2py_start_call_clock();
#endif
/*callfortranroutine*/
        (*f2py_func)(y,&n,&len_bn,&ideg,&xs,&ys,&nleft,&nright,w,&userw,rw,&ok);
if (PyErr_Occurred())
  f2py_success = 0;
#ifdef F2PY_REPORT_ATEXIT
f2py_stop_call_clock();
#endif
/*end of callfortranroutine*/
    if (f2py_success) {
/*pyobjfrom*/
/*end of pyobjfrom*/
    CFUNCSMESS("Building return value.\n");
    capi_buildvalue = Py_BuildValue("");
/*closepyobjfrom*/
/*end of closepyobjfrom*/
    } /*if (f2py_success) after callfortranroutine*/
/*cleanupfrompyobj*/
  if((PyObject *)capi_rw_tmp!=rw_capi) {
    Py_XDECREF(capi_rw_tmp); }
  }  /*if (capi_rw_tmp == NULL) ... else of rw*/
  /* End of cleaning variable rw */
  if((PyObject *)capi_w_tmp!=w_capi) {
    Py_XDECREF(capi_w_tmp); }
  }  /*if (capi_w_tmp == NULL) ... else of w*/
  /* End of cleaning variable w */
  } /*CHECKSCALAR(len(y)>=n)*/
  } /*if (f2py_success) of n*/
  /* End of cleaning variable n */
  } /*if (f2py_success) of ok*/
  /* End of cleaning variable ok */
  } /*if (f2py_success) of userw*/
  /* End of cleaning variable userw */
  } /*if (f2py_success) of nright*/
  /* End of cleaning variable nright */
  } /*if (f2py_success) of nleft*/
  /* End of cleaning variable nleft */
  } /*if (f2py_success) of ys*/
  /* End of cleaning variable ys */
  } /*if (f2py_success) of xs*/
  /* End of cleaning variable xs */
  } /*if (f2py_success) of ideg*/
  /* End of cleaning variable ideg */
  } /*if (f2py_success) of len_bn*/
  /* End of cleaning variable len_bn */
  if((PyObject *)capi_y_tmp!=y_capi) {
    Py_XDECREF(capi_y_tmp); }
  }  /*if (capi_y_tmp == NULL) ... else of y*/
  /* End of cleaning variable y */
/*end of cleanupfrompyobj*/
  if (capi_buildvalue == NULL) {
/*routdebugfailure*/
  } else {
/*routdebugleave*/
  }
  CFUNCSMESS("Freeing memory.\n");
/*freemem*/
#ifdef F2PY_REPORT_ATEXIT
f2py_stop_clock();
#endif
  return capi_buildvalue;
}
/********************************* end of est *********************************/

/************************************ fts ************************************/
static char doc_f2py_rout__stl_fts[] = "\
fts(x,np,trend,work,[n])\n\nWrapper for ``fts``.\
\n\nParameters\n----------\n"
"x : input rank-1 array('d') with bounds (n)\n"
"np : input int\n"
"trend : input rank-1 array('d') with bounds (n)\n"
"work : input rank-1 array('d') with bounds (n)\n"
"\nOther Parameters\n----------------\n"
"n : input int, optional\n    Default: len(x)";
/* extern void F_FUNC(fts,FTS)(double*,int*,int*,double*,double*); */
static PyObject *f2py_rout__stl_fts(const PyObject *capi_self,
                           PyObject *capi_args,
                           PyObject *capi_keywds,
                           void (*f2py_func)(double*,int*,int*,double*,double*)) {
  PyObject * volatile capi_buildvalue = NULL;
  volatile int f2py_success = 1;
/*decl*/

  double *x = NULL;
  npy_intp x_Dims[1] = {-1};
  const int x_Rank = 1;
  PyArrayObject *capi_x_tmp = NULL;
  int capi_x_intent = 0;
  PyObject *x_capi = Py_None;
  int n = 0;
  PyObject *n_capi = Py_None;
  int np = 0;
  PyObject *np_capi = Py_None;
  double *trend = NULL;
  npy_intp trend_Dims[1] = {-1};
  const int trend_Rank = 1;
  PyArrayObject *capi_trend_tmp = NULL;
  int capi_trend_intent = 0;
  PyObject *trend_capi = Py_None;
  double *work = NULL;
  npy_intp work_Dims[1] = {-1};
  const int work_Rank = 1;
  PyArrayObject *capi_work_tmp = NULL;
  int capi_work_intent = 0;
  PyObject *work_capi = Py_None;
  static char *capi_kwlist[] = {"x","np","trend","work","n",NULL};

/*routdebugenter*/
#ifdef F2PY_REPORT_ATEXIT
f2py_start_clock();
#endif
  if (!PyArg_ParseTupleAndKeywords(capi_args,capi_keywds,\
    "OOOO|O:_stl.fts",\
    capi_kwlist,&x_capi,&np_capi,&trend_capi,&work_capi,&n_capi))
    return NULL;
/*frompyobj*/
  /* Processing variable x */
  ;
  capi_x_intent |= F2PY_INTENT_IN;
  capi_x_tmp = array_from_pyobj(NPY_DOUBLE,x_Dims,x_Rank,capi_x_intent,x_capi);
  if (capi_x_tmp == NULL) {
    if (!PyErr_Occurred())
      PyErr_SetString(_stl_error,"failed in converting 1st argument `x' of _stl.fts to C/Fortran array" );
  } else {
    x = (double *)(PyArray_DATA(capi_x_tmp));

  /* Processing variable np */
    f2py_success = int_from_pyobj(&np,np_capi,"_stl.fts() 2nd argument (np) can't be converted to int");
  if (f2py_success) {
  /* Processing variable n */
  if (n_capi == Py_None) n = len(x); else
    f2py_success = int_from_pyobj(&n,n_capi,"_stl.fts() 1st keyword (n) can't be converted to int");
  if (f2py_success) {
  CHECKSCALAR(len(x)>=n,"len(x)>=n","1st keyword n","fts:n=%d",n) {
  /* Processing variable trend */
  trend_Dims[0]=n;
  capi_trend_intent |= F2PY_INTENT_IN;
  capi_trend_tmp = array_from_pyobj(NPY_DOUBLE,trend_Dims,trend_Rank,capi_trend_intent,trend_capi);
  if (capi_trend_tmp == NULL) {
    if (!PyErr_Occurred())
      PyErr_SetString(_stl_error,"failed in converting 3rd argument `trend' of _stl.fts to C/Fortran array" );
  } else {
    trend = (double *)(PyArray_DATA(capi_trend_tmp));

  /* Processing variable work */
  work_Dims[0]=n;
  capi_work_intent |= F2PY_INTENT_IN;
  capi_work_tmp = array_from_pyobj(NPY_DOUBLE,work_Dims,work_Rank,capi_work_intent,work_capi);
  if (capi_work_tmp == NULL) {
    if (!PyErr_Occurred())
      PyErr_SetString(_stl_error,"failed in converting 4th argument `work' of _stl.fts to C/Fortran array" );
  } else {
    work = (double *)(PyArray_DATA(capi_work_tmp));

/*end of frompyobj*/
#ifdef F2PY_REPORT_ATEXIT
f2py_start_call_clock();
#endif
/*callfortranroutine*/
        (*f2py_func)(x,&n,&np,trend,work);
if (PyErr_Occurred())
  f2py_success = 0;
#ifdef F2PY_REPORT_ATEXIT
f2py_stop_call_clock();
#endif
/*end of callfortranroutine*/
    if (f2py_success) {
/*pyobjfrom*/
/*end of pyobjfrom*/
    CFUNCSMESS("Building return value.\n");
    capi_buildvalue = Py_BuildValue("");
/*closepyobjfrom*/
/*end of closepyobjfrom*/
    } /*if (f2py_success) after callfortranroutine*/
/*cleanupfrompyobj*/
  if((PyObject *)capi_work_tmp!=work_capi) {
    Py_XDECREF(capi_work_tmp); }
  }  /*if (capi_work_tmp == NULL) ... else of work*/
  /* End of cleaning variable work */
  if((PyObject *)capi_trend_tmp!=trend_capi) {
    Py_XDECREF(capi_trend_tmp); }
  }  /*if (capi_trend_tmp == NULL) ... else of trend*/
  /* End of cleaning variable trend */
  } /*CHECKSCALAR(len(x)>=n)*/
  } /*if (f2py_success) of n*/
  /* End of cleaning variable n */
  } /*if (f2py_success) of np*/
  /* End of cleaning variable np */
  if((PyObject *)capi_x_tmp!=x_capi) {
    Py_XDECREF(capi_x_tmp); }
  }  /*if (capi_x_tmp == NULL) ... else of x*/
  /* End of cleaning variable x */
/*end of cleanupfrompyobj*/
  if (capi_buildvalue == NULL) {
/*routdebugfailure*/
  } else {
/*routdebugleave*/
  }
  CFUNCSMESS("Freeing memory.\n");
/*freemem*/
#ifdef F2PY_REPORT_ATEXIT
f2py_stop_clock();
#endif
  return capi_buildvalue;
}
/********************************* end of fts *********************************/

/************************************* ma *************************************/
static char doc_f2py_rout__stl_ma[] = "\
ma(x,len_bn,ave,[n])\n\nWrapper for ``ma``.\
\n\nParameters\n----------\n"
"x : input rank-1 array('d') with bounds (n)\n"
"len_bn : input int\n"
"ave : input rank-1 array('d') with bounds (n)\n"
"\nOther Parameters\n----------------\n"
"n : input int, optional\n    Default: len(x)";
/* extern void F_FUNC(ma,MA)(double*,int*,int*,double*); */
static PyObject *f2py_rout__stl_ma(const PyObject *capi_self,
                           PyObject *capi_args,
                           PyObject *capi_keywds,
                           void (*f2py_func)(double*,int*,int*,double*)) {
  PyObject * volatile capi_buildvalue = NULL;
  volatile int f2py_success = 1;
/*decl*/

  double *x = NULL;
  npy_intp x_Dims[1] = {-1};
  const int x_Rank = 1;
  PyArrayObject *capi_x_tmp = NULL;
  int capi_x_intent = 0;
  PyObject *x_capi = Py_None;
  int n = 0;
  PyObject *n_capi = Py_None;
  int len_bn = 0;
  PyObject *len_bn_capi = Py_None;
  double *ave = NULL;
  npy_intp ave_Dims[1] = {-1};
  const int ave_Rank = 1;
  PyArrayObject *capi_ave_tmp = NULL;
  int capi_ave_intent = 0;
  PyObject *ave_capi = Py_None;
  static char *capi_kwlist[] = {"x","len_bn","ave","n",NULL};

/*routdebugenter*/
#ifdef F2PY_REPORT_ATEXIT
f2py_start_clock();
#endif
  if (!PyArg_ParseTupleAndKeywords(capi_args,capi_keywds,\
    "OOO|O:_stl.ma",\
    capi_kwlist,&x_capi,&len_bn_capi,&ave_capi,&n_capi))
    return NULL;
/*frompyobj*/
  /* Processing variable x */
  ;
  capi_x_intent |= F2PY_INTENT_IN;
  capi_x_tmp = array_from_pyobj(NPY_DOUBLE,x_Dims,x_Rank,capi_x_intent,x_capi);
  if (capi_x_tmp == NULL) {
    if (!PyErr_Occurred())
      PyErr_SetString(_stl_error,"failed in converting 1st argument `x' of _stl.ma to C/Fortran array" );
  } else {
    x = (double *)(PyArray_DATA(capi_x_tmp));

  /* Processing variable len_bn */
    f2py_success = int_from_pyobj(&len_bn,len_bn_capi,"_stl.ma() 2nd argument (len_bn) can't be converted to int");
  if (f2py_success) {
  /* Processing variable n */
  if (n_capi == Py_None) n = len(x); else
    f2py_success = int_from_pyobj(&n,n_capi,"_stl.ma() 1st keyword (n) can't be converted to int");
  if (f2py_success) {
  CHECKSCALAR(len(x)>=n,"len(x)>=n","1st keyword n","ma:n=%d",n) {
  /* Processing variable ave */
  ave_Dims[0]=n;
  capi_ave_intent |= F2PY_INTENT_IN;
  capi_ave_tmp = array_from_pyobj(NPY_DOUBLE,ave_Dims,ave_Rank,capi_ave_intent,ave_capi);
  if (capi_ave_tmp == NULL) {
    if (!PyErr_Occurred())
      PyErr_SetString(_stl_error,"failed in converting 3rd argument `ave' of _stl.ma to C/Fortran array" );
  } else {
    ave = (double *)(PyArray_DATA(capi_ave_tmp));

/*end of frompyobj*/
#ifdef F2PY_REPORT_ATEXIT
f2py_start_call_clock();
#endif
/*callfortranroutine*/
        (*f2py_func)(x,&n,&len_bn,ave);
if (PyErr_Occurred())
  f2py_success = 0;
#ifdef F2PY_REPORT_ATEXIT
f2py_stop_call_clock();
#endif
/*end of callfortranroutine*/
    if (f2py_success) {
/*pyobjfrom*/
/*end of pyobjfrom*/
    CFUNCSMESS("Building return value.\n");
    capi_buildvalue = Py_BuildValue("");
/*closepyobjfrom*/
/*end of closepyobjfrom*/
    } /*if (f2py_success) after callfortranroutine*/
/*cleanupfrompyobj*/
  if((PyObject *)capi_ave_tmp!=ave_capi) {
    Py_XDECREF(capi_ave_tmp); }
  }  /*if (capi_ave_tmp == NULL) ... else of ave*/
  /* End of cleaning variable ave */
  } /*CHECKSCALAR(len(x)>=n)*/
  } /*if (f2py_success) of n*/
  /* End of cleaning variable n */
  } /*if (f2py_success) of len_bn*/
  /* End of cleaning variable len_bn */
  if((PyObject *)capi_x_tmp!=x_capi) {
    Py_XDECREF(capi_x_tmp); }
  }  /*if (capi_x_tmp == NULL) ... else of x*/
  /* End of cleaning variable x */
/*end of cleanupfrompyobj*/
  if (capi_buildvalue == NULL) {
/*routdebugfailure*/
  } else {
/*routdebugleave*/
  }
  CFUNCSMESS("Freeing memory.\n");
/*freemem*/
#ifdef F2PY_REPORT_ATEXIT
f2py_stop_clock();
#endif
  return capi_buildvalue;
}
/********************************* end of ma *********************************/

/*********************************** onestp ***********************************/
static char doc_f2py_rout__stl_onestp[] = "\
rw,season,trend,work = onestp(y,np,ns,nt,nl,isdeg,itdeg,ildeg,nsjump,ntjump,nljump,ni,userw,[n])\n\nWrapper for ``onestp``.\
\n\nParameters\n----------\n"
"y : input rank-1 array('d') with bounds (n)\n"
"np : input int\n"
"ns : input int\n"
"nt : input int\n"
"nl : input int\n"
"isdeg : input int\n"
"itdeg : input int\n"
"ildeg : input int\n"
"nsjump : input int\n"
"ntjump : input int\n"
"nljump : input int\n"
"ni : input int\n"
"userw : input int\n"
"\nOther Parameters\n----------------\n"
"n : input int, optional\n    Default: len(y)\n"
"\nReturns\n-------\n"
"rw : rank-1 array('d') with bounds (n)\n"
"season : rank-1 array('d') with bounds (n)\n"
"trend : rank-1 array('d') with bounds (n)\n"
"work : rank-2 array('d') with bounds (n+2*np,5)";
/* extern void F_FUNC(onestp,ONESTP)(double*,int*,int*,int*,int*,int*,int*,int*,int*,int*,int*,int*,int*,int*,double*,double*,double*,double*); */
static PyObject *f2py_rout__stl_onestp(const PyObject *capi_self,
                           PyObject *capi_args,
                           PyObject *capi_keywds,
                           void (*f2py_func)(double*,int*,int*,int*,int*,int*,int*,int*,int*,int*,int*,int*,int*,int*,double*,double*,double*,double*)) {
  PyObject * volatile capi_buildvalue = NULL;
  volatile int f2py_success = 1;
/*decl*/

  double *y = NULL;
  npy_intp y_Dims[1] = {-1};
  const int y_Rank = 1;
  PyArrayObject *capi_y_tmp = NULL;
  int capi_y_intent = 0;
  PyObject *y_capi = Py_None;
  int n = 0;
  PyObject *n_capi = Py_None;
  int np = 0;
  PyObject *np_capi = Py_None;
  int ns = 0;
  PyObject *ns_capi = Py_None;
  int nt = 0;
  PyObject *nt_capi = Py_None;
  int nl = 0;
  PyObject *nl_capi = Py_None;
  int isdeg = 0;
  PyObject *isdeg_capi = Py_None;
  int itdeg = 0;
  PyObject *itdeg_capi = Py_None;
  int ildeg = 0;
  PyObject *ildeg_capi = Py_None;
  int nsjump = 0;
  PyObject *nsjump_capi = Py_None;
  int ntjump = 0;
  PyObject *ntjump_capi = Py_None;
  int nljump = 0;
  PyObject *nljump_capi = Py_None;
  int ni = 0;
  PyObject *ni_capi = Py_None;
  int userw = 0;
  PyObject *userw_capi = Py_None;
  double *rw = NULL;
  npy_intp rw_Dims[1] = {-1};
  const int rw_Rank = 1;
  PyArrayObject *capi_rw_tmp = NULL;
  int capi_rw_intent = 0;
  double *season = NULL;
  npy_intp season_Dims[1] = {-1};
  const int season_Rank = 1;
  PyArrayObject *capi_season_tmp = NULL;
  int capi_season_intent = 0;
  double *trend = NULL;
  npy_intp trend_Dims[1] = {-1};
  const int trend_Rank = 1;
  PyArrayObject *capi_trend_tmp = NULL;
  int capi_trend_intent = 0;
  double *work = NULL;
  npy_intp work_Dims[2] = {-1, -1};
  const int work_Rank = 2;
  PyArrayObject *capi_work_tmp = NULL;
  int capi_work_intent = 0;
  static char *capi_kwlist[] = {"y","np","ns","nt","nl","isdeg","itdeg","ildeg","nsjump","ntjump","nljump","ni","userw","n",NULL};

/*routdebugenter*/
#ifdef F2PY_REPORT_ATEXIT
f2py_start_clock();
#endif
  if (!PyArg_ParseTupleAndKeywords(capi_args,capi_keywds,\
    "OOOOOOOOOOOOO|O:_stl.onestp",\
    capi_kwlist,&y_capi,&np_capi,&ns_capi,&nt_capi,&nl_capi,&isdeg_capi,&itdeg_capi,&ildeg_capi,&nsjump_capi,&ntjump_capi,&nljump_capi,&ni_capi,&userw_capi,&n_capi))
    return NULL;
/*frompyobj*/
  /* Processing variable y */
  ;
  capi_y_intent |= F2PY_INTENT_IN;
  capi_y_tmp = array_from_pyobj(NPY_DOUBLE,y_Dims,y_Rank,capi_y_intent,y_capi);
  if (capi_y_tmp == NULL) {
    if (!PyErr_Occurred())
      PyErr_SetString(_stl_error,"failed in converting 1st argument `y' of _stl.onestp to C/Fortran array" );
  } else {
    y = (double *)(PyArray_DATA(capi_y_tmp));

  /* Processing variable np */
    f2py_success = int_from_pyobj(&np,np_capi,"_stl.onestp() 2nd argument (np) can't be converted to int");
  if (f2py_success) {
  /* Processing variable ns */
    f2py_success = int_from_pyobj(&ns,ns_capi,"_stl.onestp() 3rd argument (ns) can't be converted to int");
  if (f2py_success) {
  /* Processing variable nt */
    f2py_success = int_from_pyobj(&nt,nt_capi,"_stl.onestp() 4th argument (nt) can't be converted to int");
  if (f2py_success) {
  /* Processing variable nl */
    f2py_success = int_from_pyobj(&nl,nl_capi,"_stl.onestp() 5th argument (nl) can't be converted to int");
  if (f2py_success) {
  /* Processing variable isdeg */
    f2py_success = int_from_pyobj(&isdeg,isdeg_capi,"_stl.onestp() 6th argument (isdeg) can't be converted to int");
  if (f2py_success) {
  /* Processing variable itdeg */
    f2py_success = int_from_pyobj(&itdeg,itdeg_capi,"_stl.onestp() 7th argument (itdeg) can't be converted to int");
  if (f2py_success) {
  /* Processing variable ildeg */
    f2py_success = int_from_pyobj(&ildeg,ildeg_capi,"_stl.onestp() 8th argument (ildeg) can't be converted to int");
  if (f2py_success) {
  /* Processing variable nsjump */
    f2py_success = int_from_pyobj(&nsjump,nsjump_capi,"_stl.onestp() 9th argument (nsjump) can't be converted to int");
  if (f2py_success) {
  /* Processing variable ntjump */
    f2py_success = int_from_pyobj(&ntjump,ntjump_capi,"_stl.onestp() 10th argument (ntjump) can't be converted to int");
  if (f2py_success) {
  /* Processing variable nljump */
    f2py_success = int_from_pyobj(&nljump,nljump_capi,"_stl.onestp() 11st argument (nljump) can't be converted to int");
  if (f2py_success) {
  /* Processing variable ni */
    f2py_success = int_from_pyobj(&ni,ni_capi,"_stl.onestp() 12nd argument (ni) can't be converted to int");
  if (f2py_success) {
  /* Processing variable userw */
    userw = (int)PyObject_IsTrue(userw_capi);
    f2py_success = 1;
  if (f2py_success) {
  /* Processing variable n */
  if (n_capi == Py_None) n = len(y); else
    f2py_success = int_from_pyobj(&n,n_capi,"_stl.onestp() 1st keyword (n) can't be converted to int");
  if (f2py_success) {
  CHECKSCALAR(len(y)>=n,"len(y)>=n","1st keyword n","onestp:n=%d",n) {
  /* Processing variable rw */
  rw_Dims[0]=n;
  capi_rw_intent |= F2PY_INTENT_OUT|F2PY_INTENT_HIDE;
  capi_rw_tmp = array_from_pyobj(NPY_DOUBLE,rw_Dims,rw_Rank,capi_rw_intent,Py_None);
  if (capi_rw_tmp == NULL) {
    if (!PyErr_Occurred())
      PyErr_SetString(_stl_error,"failed in converting hidden `rw' of _stl.onestp to C/Fortran array" );
  } else {
    rw = (double *)(PyArray_DATA(capi_rw_tmp));

  /* Processing variable season */
  season_Dims[0]=n;
  capi_season_intent |= F2PY_INTENT_OUT|F2PY_INTENT_HIDE;
  capi_season_tmp = array_from_pyobj(NPY_DOUBLE,season_Dims,season_Rank,capi_season_intent,Py_None);
  if (capi_season_tmp == NULL) {
    if (!PyErr_Occurred())
      PyErr_SetString(_stl_error,"failed in converting hidden `season' of _stl.onestp to C/Fortran array" );
  } else {
    season = (double *)(PyArray_DATA(capi_season_tmp));

  /* Processing variable trend */
  trend_Dims[0]=n;
  capi_trend_intent |= F2PY_INTENT_OUT|F2PY_INTENT_HIDE;
  capi_trend_tmp = array_from_pyobj(NPY_DOUBLE,trend_Dims,trend_Rank,capi_trend_intent,Py_None);
  if (capi_trend_tmp == NULL) {
    if (!PyErr_Occurred())
      PyErr_SetString(_stl_error,"failed in converting hidden `trend' of _stl.onestp to C/Fortran array" );
  } else {
    trend = (double *)(PyArray_DATA(capi_trend_tmp));

  /* Processing variable work */
  work_Dims[0]=n+2*np,work_Dims[1]=5;
  capi_work_intent |= F2PY_INTENT_OUT|F2PY_INTENT_HIDE;
  capi_work_tmp = array_from_pyobj(NPY_DOUBLE,work_Dims,work_Rank,capi_work_intent,Py_None);
  if (capi_work_tmp == NULL) {
    if (!PyErr_Occurred())
      PyErr_SetString(_stl_error,"failed in converting hidden `work' of _stl.onestp to C/Fortran array" );
  } else {
    work = (double *)(PyArray_DATA(capi_work_tmp));

/*end of frompyobj*/
#ifdef F2PY_REPORT_ATEXIT
f2py_start_call_clock();
#endif
/*callfortranroutine*/
        (*f2py_func)(y,&n,&np,&ns,&nt,&nl,&isdeg,&itdeg,&ildeg,&nsjump,&ntjump,&nljump,&ni,&userw,rw,season,trend,work);
if (PyErr_Occurred())
  f2py_success = 0;
#ifdef F2PY_REPORT_ATEXIT
f2py_stop_call_clock();
#endif
/*end of callfortranroutine*/
    if (f2py_success) {
/*pyobjfrom*/
/*end of pyobjfrom*/
    CFUNCSMESS("Building return value.\n");
    capi_buildvalue = Py_BuildValue("NNNN",capi_rw_tmp,capi_season_tmp,capi_trend_tmp,capi_work_tmp);
/*closepyobjfrom*/
/*end of closepyobjfrom*/
    } /*if (f2py_success) after callfortranroutine*/
/*cleanupfrompyobj*/
  }  /*if (capi_work_tmp == NULL) ... else of work*/
  /* End of cleaning variable work */
  }  /*if (capi_trend_tmp == NULL) ... else of trend*/
  /* End of cleaning variable trend */
  }  /*if (capi_season_tmp == NULL) ... else of season*/
  /* End of cleaning variable season */
  }  /*if (capi_rw_tmp == NULL) ... else of rw*/
  /* End of cleaning variable rw */
  } /*CHECKSCALAR(len(y)>=n)*/
  } /*if (f2py_success) of n*/
  /* End of cleaning variable n */
  } /*if (f2py_success) of userw*/
  /* End of cleaning variable userw */
  } /*if (f2py_success) of ni*/
  /* End of cleaning variable ni */
  } /*if (f2py_success) of nljump*/
  /* End of cleaning variable nljump */
  } /*if (f2py_success) of ntjump*/
  /* End of cleaning variable ntjump */
  } /*if (f2py_success) of nsjump*/
  /* End of cleaning variable nsjump */
  } /*if (f2py_success) of ildeg*/
  /* End of cleaning variable ildeg */
  } /*if (f2py_success) of itdeg*/
  /* End of cleaning variable itdeg */
  } /*if (f2py_success) of isdeg*/
  /* End of cleaning variable isdeg */
  } /*if (f2py_success) of nl*/
  /* End of cleaning variable nl */
  } /*if (f2py_success) of nt*/
  /* End of cleaning variable nt */
  } /*if (f2py_success) of ns*/
  /* End of cleaning variable ns */
  } /*if (f2py_success) of np*/
  /* End of cleaning variable np */
  if((PyObject *)capi_y_tmp!=y_capi) {
    Py_XDECREF(capi_y_tmp); }
  }  /*if (capi_y_tmp == NULL) ... else of y*/
  /* End of cleaning variable y */
/*end of cleanupfrompyobj*/
  if (capi_buildvalue == NULL) {
/*routdebugfailure*/
  } else {
/*routdebugleave*/
  }
  CFUNCSMESS("Freeing memory.\n");
/*freemem*/
#ifdef F2PY_REPORT_ATEXIT
f2py_stop_clock();
#endif
  return capi_buildvalue;
}
/******************************* end of onestp *******************************/

/************************************ rwts ************************************/
static char doc_f2py_rout__stl_rwts[] = "\
rwts(y,fit,rw,[n])\n\nWrapper for ``rwts``.\
\n\nParameters\n----------\n"
"y : input rank-1 array('d') with bounds (n)\n"
"fit : input rank-1 array('d') with bounds (n)\n"
"rw : input rank-1 array('d') with bounds (n)\n"
"\nOther Parameters\n----------------\n"
"n : input int, optional\n    Default: len(y)";
/* extern void F_FUNC(rwts,RWTS)(double*,int*,double*,double*); */
static PyObject *f2py_rout__stl_rwts(const PyObject *capi_self,
                           PyObject *capi_args,
                           PyObject *capi_keywds,
                           void (*f2py_func)(double*,int*,double*,double*)) {
  PyObject * volatile capi_buildvalue = NULL;
  volatile int f2py_success = 1;
/*decl*/

  double *y = NULL;
  npy_intp y_Dims[1] = {-1};
  const int y_Rank = 1;
  PyArrayObject *capi_y_tmp = NULL;
  int capi_y_intent = 0;
  PyObject *y_capi = Py_None;
  int n = 0;
  PyObject *n_capi = Py_None;
  double *fit = NULL;
  npy_intp fit_Dims[1] = {-1};
  const int fit_Rank = 1;
  PyArrayObject *capi_fit_tmp = NULL;
  int capi_fit_intent = 0;
  PyObject *fit_capi = Py_None;
  double *rw = NULL;
  npy_intp rw_Dims[1] = {-1};
  const int rw_Rank = 1;
  PyArrayObject *capi_rw_tmp = NULL;
  int capi_rw_intent = 0;
  PyObject *rw_capi = Py_None;
  static char *capi_kwlist[] = {"y","fit","rw","n",NULL};

/*routdebugenter*/
#ifdef F2PY_REPORT_ATEXIT
f2py_start_clock();
#endif
  if (!PyArg_ParseTupleAndKeywords(capi_args,capi_keywds,\
    "OOO|O:_stl.rwts",\
    capi_kwlist,&y_capi,&fit_capi,&rw_capi,&n_capi))
    return NULL;
/*frompyobj*/
  /* Processing variable y */
  ;
  capi_y_intent |= F2PY_INTENT_IN;
  capi_y_tmp = array_from_pyobj(NPY_DOUBLE,y_Dims,y_Rank,capi_y_intent,y_capi);
  if (capi_y_tmp == NULL) {
    if (!PyErr_Occurred())
      PyErr_SetString(_stl_error,"failed in converting 1st argument `y' of _stl.rwts to C/Fortran array" );
  } else {
    y = (double *)(PyArray_DATA(capi_y_tmp));

  /* Processing variable n */
  if (n_capi == Py_None) n = len(y); else
    f2py_success = int_from_pyobj(&n,n_capi,"_stl.rwts() 1st keyword (n) can't be converted to int");
  if (f2py_success) {
  CHECKSCALAR(len(y)>=n,"len(y)>=n","1st keyword n","rwts:n=%d",n) {
  /* Processing variable fit */
  fit_Dims[0]=n;
  capi_fit_intent |= F2PY_INTENT_IN;
  capi_fit_tmp = array_from_pyobj(NPY_DOUBLE,fit_Dims,fit_Rank,capi_fit_intent,fit_capi);
  if (capi_fit_tmp == NULL) {
    if (!PyErr_Occurred())
      PyErr_SetString(_stl_error,"failed in converting 2nd argument `fit' of _stl.rwts to C/Fortran array" );
  } else {
    fit = (double *)(PyArray_DATA(capi_fit_tmp));

  /* Processing variable rw */
  rw_Dims[0]=n;
  capi_rw_intent |= F2PY_INTENT_IN;
  capi_rw_tmp = array_from_pyobj(NPY_DOUBLE,rw_Dims,rw_Rank,capi_rw_intent,rw_capi);
  if (capi_rw_tmp == NULL) {
    if (!PyErr_Occurred())
      PyErr_SetString(_stl_error,"failed in converting 3rd argument `rw' of _stl.rwts to C/Fortran array" );
  } else {
    rw = (double *)(PyArray_DATA(capi_rw_tmp));

/*end of frompyobj*/
#ifdef F2PY_REPORT_ATEXIT
f2py_start_call_clock();
#endif
/*callfortranroutine*/
        (*f2py_func)(y,&n,fit,rw);
if (PyErr_Occurred())
  f2py_success = 0;
#ifdef F2PY_REPORT_ATEXIT
f2py_stop_call_clock();
#endif
/*end of callfortranroutine*/
    if (f2py_success) {
/*pyobjfrom*/
/*end of pyobjfrom*/
    CFUNCSMESS("Building return value.\n");
    capi_buildvalue = Py_BuildValue("");
/*closepyobjfrom*/
/*end of closepyobjfrom*/
    } /*if (f2py_success) after callfortranroutine*/
/*cleanupfrompyobj*/
  if((PyObject *)capi_rw_tmp!=rw_capi) {
    Py_XDECREF(capi_rw_tmp); }
  }  /*if (capi_rw_tmp == NULL) ... else of rw*/
  /* End of cleaning variable rw */
  if((PyObject *)capi_fit_tmp!=fit_capi) {
    Py_XDECREF(capi_fit_tmp); }
  }  /*if (capi_fit_tmp == NULL) ... else of fit*/
  /* End of cleaning variable fit */
  } /*CHECKSCALAR(len(y)>=n)*/
  } /*if (f2py_success) of n*/
  /* End of cleaning variable n */
  if((PyObject *)capi_y_tmp!=y_capi) {
    Py_XDECREF(capi_y_tmp); }
  }  /*if (capi_y_tmp == NULL) ... else of y*/
  /* End of cleaning variable y */
/*end of cleanupfrompyobj*/
  if (capi_buildvalue == NULL) {
/*routdebugfailure*/
  } else {
/*routdebugleave*/
  }
  CFUNCSMESS("Freeing memory.\n");
/*freemem*/
#ifdef F2PY_REPORT_ATEXIT
f2py_stop_clock();
#endif
  return capi_buildvalue;
}
/******************************** end of rwts ********************************/

/************************************* ss *************************************/
static char doc_f2py_rout__stl_ss[] = "\
ss(y,np,ns,isdeg,nsjump,userw,rw,season,work1,work2,work3,work4,[n])\n\nWrapper for ``ss``.\
\n\nParameters\n----------\n"
"y : input rank-1 array('d') with bounds (n)\n"
"np : input int\n"
"ns : input int\n"
"isdeg : input int\n"
"nsjump : input int\n"
"userw : input int\n"
"rw : input rank-1 array('d') with bounds (n)\n"
"season : input rank-1 array('d') with bounds (n+2*np)\n"
"work1 : input rank-1 array('d') with bounds (n)\n"
"work2 : input rank-1 array('d') with bounds (n)\n"
"work3 : input rank-1 array('d') with bounds (n)\n"
"work4 : input rank-1 array('d') with bounds (n)\n"
"\nOther Parameters\n----------------\n"
"n : input int, optional\n    Default: len(y)";
/* extern void F_FUNC(ss,SS)(double*,int*,int*,int*,int*,int*,int*,double*,double*,double*,double*,double*,double*); */
static PyObject *f2py_rout__stl_ss(const PyObject *capi_self,
                           PyObject *capi_args,
                           PyObject *capi_keywds,
                           void (*f2py_func)(double*,int*,int*,int*,int*,int*,int*,double*,double*,double*,double*,double*,double*)) {
  PyObject * volatile capi_buildvalue = NULL;
  volatile int f2py_success = 1;
/*decl*/

  double *y = NULL;
  npy_intp y_Dims[1] = {-1};
  const int y_Rank = 1;
  PyArrayObject *capi_y_tmp = NULL;
  int capi_y_intent = 0;
  PyObject *y_capi = Py_None;
  int n = 0;
  PyObject *n_capi = Py_None;
  int np = 0;
  PyObject *np_capi = Py_None;
  int ns = 0;
  PyObject *ns_capi = Py_None;
  int isdeg = 0;
  PyObject *isdeg_capi = Py_None;
  int nsjump = 0;
  PyObject *nsjump_capi = Py_None;
  int userw = 0;
  PyObject *userw_capi = Py_None;
  double *rw = NULL;
  npy_intp rw_Dims[1] = {-1};
  const int rw_Rank = 1;
  PyArrayObject *capi_rw_tmp = NULL;
  int capi_rw_intent = 0;
  PyObject *rw_capi = Py_None;
  double *season = NULL;
  npy_intp season_Dims[1] = {-1};
  const int season_Rank = 1;
  PyArrayObject *capi_season_tmp = NULL;
  int capi_season_intent = 0;
  PyObject *season_capi = Py_None;
  double *work1 = NULL;
  npy_intp work1_Dims[1] = {-1};
  const int work1_Rank = 1;
  PyArrayObject *capi_work1_tmp = NULL;
  int capi_work1_intent = 0;
  PyObject *work1_capi = Py_None;
  double *work2 = NULL;
  npy_intp work2_Dims[1] = {-1};
  const int work2_Rank = 1;
  PyArrayObject *capi_work2_tmp = NULL;
  int capi_work2_intent = 0;
  PyObject *work2_capi = Py_None;
  double *work3 = NULL;
  npy_intp work3_Dims[1] = {-1};
  const int work3_Rank = 1;
  PyArrayObject *capi_work3_tmp = NULL;
  int capi_work3_intent = 0;
  PyObject *work3_capi = Py_None;
  double *work4 = NULL;
  npy_intp work4_Dims[1] = {-1};
  const int work4_Rank = 1;
  PyArrayObject *capi_work4_tmp = NULL;
  int capi_work4_intent = 0;
  PyObject *work4_capi = Py_None;
  static char *capi_kwlist[] = {"y","np","ns","isdeg","nsjump","userw","rw","season","work1","work2","work3","work4","n",NULL};

/*routdebugenter*/
#ifdef F2PY_REPORT_ATEXIT
f2py_start_clock();
#endif
  if (!PyArg_ParseTupleAndKeywords(capi_args,capi_keywds,\
    "OOOOOOOOOOOO|O:_stl.ss",\
    capi_kwlist,&y_capi,&np_capi,&ns_capi,&isdeg_capi,&nsjump_capi,&userw_capi,&rw_capi,&season_capi,&work1_capi,&work2_capi,&work3_capi,&work4_capi,&n_capi))
    return NULL;
/*frompyobj*/
  /* Processing variable y */
  ;
  capi_y_intent |= F2PY_INTENT_IN;
  capi_y_tmp = array_from_pyobj(NPY_DOUBLE,y_Dims,y_Rank,capi_y_intent,y_capi);
  if (capi_y_tmp == NULL) {
    if (!PyErr_Occurred())
      PyErr_SetString(_stl_error,"failed in converting 1st argument `y' of _stl.ss to C/Fortran array" );
  } else {
    y = (double *)(PyArray_DATA(capi_y_tmp));

  /* Processing variable np */
    f2py_success = int_from_pyobj(&np,np_capi,"_stl.ss() 2nd argument (np) can't be converted to int");
  if (f2py_success) {
  /* Processing variable ns */
    f2py_success = int_from_pyobj(&ns,ns_capi,"_stl.ss() 3rd argument (ns) can't be converted to int");
  if (f2py_success) {
  /* Processing variable isdeg */
    f2py_success = int_from_pyobj(&isdeg,isdeg_capi,"_stl.ss() 4th argument (isdeg) can't be converted to int");
  if (f2py_success) {
  /* Processing variable nsjump */
    f2py_success = int_from_pyobj(&nsjump,nsjump_capi,"_stl.ss() 5th argument (nsjump) can't be converted to int");
  if (f2py_success) {
  /* Processing variable userw */
    userw = (int)PyObject_IsTrue(userw_capi);
    f2py_success = 1;
  if (f2py_success) {
  /* Processing variable n */
  if (n_capi == Py_None) n = len(y); else
    f2py_success = int_from_pyobj(&n,n_capi,"_stl.ss() 1st keyword (n) can't be converted to int");
  if (f2py_success) {
  CHECKSCALAR(len(y)>=n,"len(y)>=n","1st keyword n","ss:n=%d",n) {
  /* Processing variable rw */
  rw_Dims[0]=n;
  capi_rw_intent |= F2PY_INTENT_IN;
  capi_rw_tmp = array_from_pyobj(NPY_DOUBLE,rw_Dims,rw_Rank,capi_rw_intent,rw_capi);
  if (capi_rw_tmp == NULL) {
    if (!PyErr_Occurred())
      PyErr_SetString(_stl_error,"failed in converting 7th argument `rw' of _stl.ss to C/Fortran array" );
  } else {
    rw = (double *)(PyArray_DATA(capi_rw_tmp));

  /* Processing variable season */
  season_Dims[0]=n+2*np;
  capi_season_intent |= F2PY_INTENT_IN;
  capi_season_tmp = array_from_pyobj(NPY_DOUBLE,season_Dims,season_Rank,capi_season_intent,season_capi);
  if (capi_season_tmp == NULL) {
    if (!PyErr_Occurred())
      PyErr_SetString(_stl_error,"failed in converting 8th argument `season' of _stl.ss to C/Fortran array" );
  } else {
    season = (double *)(PyArray_DATA(capi_season_tmp));

  /* Processing variable work1 */
  work1_Dims[0]=n;
  capi_work1_intent |= F2PY_INTENT_IN;
  capi_work1_tmp = array_from_pyobj(NPY_DOUBLE,work1_Dims,work1_Rank,capi_work1_intent,work1_capi);
  if (capi_work1_tmp == NULL) {
    if (!PyErr_Occurred())
      PyErr_SetString(_stl_error,"failed in converting 9th argument `work1' of _stl.ss to C/Fortran array" );
  } else {
    work1 = (double *)(PyArray_DATA(capi_work1_tmp));

  /* Processing variable work2 */
  work2_Dims[0]=n;
  capi_work2_intent |= F2PY_INTENT_IN;
  capi_work2_tmp = array_from_pyobj(NPY_DOUBLE,work2_Dims,work2_Rank,capi_work2_intent,work2_capi);
  if (capi_work2_tmp == NULL) {
    if (!PyErr_Occurred())
      PyErr_SetString(_stl_error,"failed in converting 10th argument `work2' of _stl.ss to C/Fortran array" );
  } else {
    work2 = (double *)(PyArray_DATA(capi_work2_tmp));

  /* Processing variable work3 */
  work3_Dims[0]=n;
  capi_work3_intent |= F2PY_INTENT_IN;
  capi_work3_tmp = array_from_pyobj(NPY_DOUBLE,work3_Dims,work3_Rank,capi_work3_intent,work3_capi);
  if (capi_work3_tmp == NULL) {
    if (!PyErr_Occurred())
      PyErr_SetString(_stl_error,"failed in converting 11st argument `work3' of _stl.ss to C/Fortran array" );
  } else {
    work3 = (double *)(PyArray_DATA(capi_work3_tmp));

  /* Processing variable work4 */
  work4_Dims[0]=n;
  capi_work4_intent |= F2PY_INTENT_IN;
  capi_work4_tmp = array_from_pyobj(NPY_DOUBLE,work4_Dims,work4_Rank,capi_work4_intent,work4_capi);
  if (capi_work4_tmp == NULL) {
    if (!PyErr_Occurred())
      PyErr_SetString(_stl_error,"failed in converting 12nd argument `work4' of _stl.ss to C/Fortran array" );
  } else {
    work4 = (double *)(PyArray_DATA(capi_work4_tmp));

/*end of frompyobj*/
#ifdef F2PY_REPORT_ATEXIT
f2py_start_call_clock();
#endif
/*callfortranroutine*/
        (*f2py_func)(y,&n,&np,&ns,&isdeg,&nsjump,&userw,rw,season,work1,work2,work3,work4);
if (PyErr_Occurred())
  f2py_success = 0;
#ifdef F2PY_REPORT_ATEXIT
f2py_stop_call_clock();
#endif
/*end of callfortranroutine*/
    if (f2py_success) {
/*pyobjfrom*/
/*end of pyobjfrom*/
    CFUNCSMESS("Building return value.\n");
    capi_buildvalue = Py_BuildValue("");
/*closepyobjfrom*/
/*end of closepyobjfrom*/
    } /*if (f2py_success) after callfortranroutine*/
/*cleanupfrompyobj*/
  if((PyObject *)capi_work4_tmp!=work4_capi) {
    Py_XDECREF(capi_work4_tmp); }
  }  /*if (capi_work4_tmp == NULL) ... else of work4*/
  /* End of cleaning variable work4 */
  if((PyObject *)capi_work3_tmp!=work3_capi) {
    Py_XDECREF(capi_work3_tmp); }
  }  /*if (capi_work3_tmp == NULL) ... else of work3*/
  /* End of cleaning variable work3 */
  if((PyObject *)capi_work2_tmp!=work2_capi) {
    Py_XDECREF(capi_work2_tmp); }
  }  /*if (capi_work2_tmp == NULL) ... else of work2*/
  /* End of cleaning variable work2 */
  if((PyObject *)capi_work1_tmp!=work1_capi) {
    Py_XDECREF(capi_work1_tmp); }
  }  /*if (capi_work1_tmp == NULL) ... else of work1*/
  /* End of cleaning variable work1 */
  if((PyObject *)capi_season_tmp!=season_capi) {
    Py_XDECREF(capi_season_tmp); }
  }  /*if (capi_season_tmp == NULL) ... else of season*/
  /* End of cleaning variable season */
  if((PyObject *)capi_rw_tmp!=rw_capi) {
    Py_XDECREF(capi_rw_tmp); }
  }  /*if (capi_rw_tmp == NULL) ... else of rw*/
  /* End of cleaning variable rw */
  } /*CHECKSCALAR(len(y)>=n)*/
  } /*if (f2py_success) of n*/
  /* End of cleaning variable n */
  } /*if (f2py_success) of userw*/
  /* End of cleaning variable userw */
  } /*if (f2py_success) of nsjump*/
  /* End of cleaning variable nsjump */
  } /*if (f2py_success) of isdeg*/
  /* End of cleaning variable isdeg */
  } /*if (f2py_success) of ns*/
  /* End of cleaning variable ns */
  } /*if (f2py_success) of np*/
  /* End of cleaning variable np */
  if((PyObject *)capi_y_tmp!=y_capi) {
    Py_XDECREF(capi_y_tmp); }
  }  /*if (capi_y_tmp == NULL) ... else of y*/
  /* End of cleaning variable y */
/*end of cleanupfrompyobj*/
  if (capi_buildvalue == NULL) {
/*routdebugfailure*/
  } else {
/*routdebugleave*/
  }
  CFUNCSMESS("Freeing memory.\n");
/*freemem*/
#ifdef F2PY_REPORT_ATEXIT
f2py_stop_clock();
#endif
  return capi_buildvalue;
}
/********************************* end of ss *********************************/

/*********************************** stlez ***********************************/
static char doc_f2py_rout__stl_stlez[] = "\
stlez(y,np,ns,isdeg,itdeg,robust,no,rw,season,trend,work,[n])\n\nWrapper for ``stlez``.\
\n\nParameters\n----------\n"
"y : input rank-1 array('d') with bounds (n)\n"
"np : input int\n"
"ns : input int\n"
"isdeg : input int\n"
"itdeg : input int\n"
"robust : input int\n"
"no : input int\n"
"rw : input rank-1 array('d') with bounds (n)\n"
"season : input rank-1 array('d') with bounds (n)\n"
"trend : input rank-1 array('d') with bounds (n)\n"
"work : input rank-2 array('d') with bounds (n+2*np,7)\n"
"\nOther Parameters\n----------------\n"
"n : input int, optional\n    Default: len(y)";
/* extern void F_FUNC(stlez,STLEZ)(double*,int*,int*,int*,int*,int*,int*,int*,double*,double*,double*,double*); */
static PyObject *f2py_rout__stl_stlez(const PyObject *capi_self,
                           PyObject *capi_args,
                           PyObject *capi_keywds,
                           void (*f2py_func)(double*,int*,int*,int*,int*,int*,int*,int*,double*,double*,double*,double*)) {
  PyObject * volatile capi_buildvalue = NULL;
  volatile int f2py_success = 1;
/*decl*/

  double *y = NULL;
  npy_intp y_Dims[1] = {-1};
  const int y_Rank = 1;
  PyArrayObject *capi_y_tmp = NULL;
  int capi_y_intent = 0;
  PyObject *y_capi = Py_None;
  int n = 0;
  PyObject *n_capi = Py_None;
  int np = 0;
  PyObject *np_capi = Py_None;
  int ns = 0;
  PyObject *ns_capi = Py_None;
  int isdeg = 0;
  PyObject *isdeg_capi = Py_None;
  int itdeg = 0;
  PyObject *itdeg_capi = Py_None;
  int robust = 0;
  PyObject *robust_capi = Py_None;
  int no = 0;
  PyObject *no_capi = Py_None;
  double *rw = NULL;
  npy_intp rw_Dims[1] = {-1};
  const int rw_Rank = 1;
  PyArrayObject *capi_rw_tmp = NULL;
  int capi_rw_intent = 0;
  PyObject *rw_capi = Py_None;
  double *season = NULL;
  npy_intp season_Dims[1] = {-1};
  const int season_Rank = 1;
  PyArrayObject *capi_season_tmp = NULL;
  int capi_season_intent = 0;
  PyObject *season_capi = Py_None;
  double *trend = NULL;
  npy_intp trend_Dims[1] = {-1};
  const int trend_Rank = 1;
  PyArrayObject *capi_trend_tmp = NULL;
  int capi_trend_intent = 0;
  PyObject *trend_capi = Py_None;
  double *work = NULL;
  npy_intp work_Dims[2] = {-1, -1};
  const int work_Rank = 2;
  PyArrayObject *capi_work_tmp = NULL;
  int capi_work_intent = 0;
  PyObject *work_capi = Py_None;
  static char *capi_kwlist[] = {"y","np","ns","isdeg","itdeg","robust","no","rw","season","trend","work","n",NULL};

/*routdebugenter*/
#ifdef F2PY_REPORT_ATEXIT
f2py_start_clock();
#endif
  if (!PyArg_ParseTupleAndKeywords(capi_args,capi_keywds,\
    "OOOOOOOOOOO|O:_stl.stlez",\
    capi_kwlist,&y_capi,&np_capi,&ns_capi,&isdeg_capi,&itdeg_capi,&robust_capi,&no_capi,&rw_capi,&season_capi,&trend_capi,&work_capi,&n_capi))
    return NULL;
/*frompyobj*/
  /* Processing variable y */
  ;
  capi_y_intent |= F2PY_INTENT_IN;
  capi_y_tmp = array_from_pyobj(NPY_DOUBLE,y_Dims,y_Rank,capi_y_intent,y_capi);
  if (capi_y_tmp == NULL) {
    if (!PyErr_Occurred())
      PyErr_SetString(_stl_error,"failed in converting 1st argument `y' of _stl.stlez to C/Fortran array" );
  } else {
    y = (double *)(PyArray_DATA(capi_y_tmp));

  /* Processing variable np */
    f2py_success = int_from_pyobj(&np,np_capi,"_stl.stlez() 2nd argument (np) can't be converted to int");
  if (f2py_success) {
  /* Processing variable ns */
    f2py_success = int_from_pyobj(&ns,ns_capi,"_stl.stlez() 3rd argument (ns) can't be converted to int");
  if (f2py_success) {
  /* Processing variable isdeg */
    f2py_success = int_from_pyobj(&isdeg,isdeg_capi,"_stl.stlez() 4th argument (isdeg) can't be converted to int");
  if (f2py_success) {
  /* Processing variable itdeg */
    f2py_success = int_from_pyobj(&itdeg,itdeg_capi,"_stl.stlez() 5th argument (itdeg) can't be converted to int");
  if (f2py_success) {
  /* Processing variable robust */
    robust = (int)PyObject_IsTrue(robust_capi);
    f2py_success = 1;
  if (f2py_success) {
  /* Processing variable no */
    f2py_success = int_from_pyobj(&no,no_capi,"_stl.stlez() 7th argument (no) can't be converted to int");
  if (f2py_success) {
  /* Processing variable n */
  if (n_capi == Py_None) n = len(y); else
    f2py_success = int_from_pyobj(&n,n_capi,"_stl.stlez() 1st keyword (n) can't be converted to int");
  if (f2py_success) {
  CHECKSCALAR(len(y)>=n,"len(y)>=n","1st keyword n","stlez:n=%d",n) {
  /* Processing variable rw */
  rw_Dims[0]=n;
  capi_rw_intent |= F2PY_INTENT_IN;
  capi_rw_tmp = array_from_pyobj(NPY_DOUBLE,rw_Dims,rw_Rank,capi_rw_intent,rw_capi);
  if (capi_rw_tmp == NULL) {
    if (!PyErr_Occurred())
      PyErr_SetString(_stl_error,"failed in converting 8th argument `rw' of _stl.stlez to C/Fortran array" );
  } else {
    rw = (double *)(PyArray_DATA(capi_rw_tmp));

  /* Processing variable season */
  season_Dims[0]=n;
  capi_season_intent |= F2PY_INTENT_IN;
  capi_season_tmp = array_from_pyobj(NPY_DOUBLE,season_Dims,season_Rank,capi_season_intent,season_capi);
  if (capi_season_tmp == NULL) {
    if (!PyErr_Occurred())
      PyErr_SetString(_stl_error,"failed in converting 9th argument `season' of _stl.stlez to C/Fortran array" );
  } else {
    season = (double *)(PyArray_DATA(capi_season_tmp));

  /* Processing variable trend */
  trend_Dims[0]=n;
  capi_trend_intent |= F2PY_INTENT_IN;
  capi_trend_tmp = array_from_pyobj(NPY_DOUBLE,trend_Dims,trend_Rank,capi_trend_intent,trend_capi);
  if (capi_trend_tmp == NULL) {
    if (!PyErr_Occurred())
      PyErr_SetString(_stl_error,"failed in converting 10th argument `trend' of _stl.stlez to C/Fortran array" );
  } else {
    trend = (double *)(PyArray_DATA(capi_trend_tmp));

  /* Processing variable work */
  work_Dims[0]=n+2*np,work_Dims[1]=7;
  capi_work_intent |= F2PY_INTENT_IN;
  capi_work_tmp = array_from_pyobj(NPY_DOUBLE,work_Dims,work_Rank,capi_work_intent,work_capi);
  if (capi_work_tmp == NULL) {
    if (!PyErr_Occurred())
      PyErr_SetString(_stl_error,"failed in converting 11st argument `work' of _stl.stlez to C/Fortran array" );
  } else {
    work = (double *)(PyArray_DATA(capi_work_tmp));

/*end of frompyobj*/
#ifdef F2PY_REPORT_ATEXIT
f2py_start_call_clock();
#endif
/*callfortranroutine*/
        (*f2py_func)(y,&n,&np,&ns,&isdeg,&itdeg,&robust,&no,rw,season,trend,work);
if (PyErr_Occurred())
  f2py_success = 0;
#ifdef F2PY_REPORT_ATEXIT
f2py_stop_call_clock();
#endif
/*end of callfortranroutine*/
    if (f2py_success) {
/*pyobjfrom*/
/*end of pyobjfrom*/
    CFUNCSMESS("Building return value.\n");
    capi_buildvalue = Py_BuildValue("");
/*closepyobjfrom*/
/*end of closepyobjfrom*/
    } /*if (f2py_success) after callfortranroutine*/
/*cleanupfrompyobj*/
  if((PyObject *)capi_work_tmp!=work_capi) {
    Py_XDECREF(capi_work_tmp); }
  }  /*if (capi_work_tmp == NULL) ... else of work*/
  /* End of cleaning variable work */
  if((PyObject *)capi_trend_tmp!=trend_capi) {
    Py_XDECREF(capi_trend_tmp); }
  }  /*if (capi_trend_tmp == NULL) ... else of trend*/
  /* End of cleaning variable trend */
  if((PyObject *)capi_season_tmp!=season_capi) {
    Py_XDECREF(capi_season_tmp); }
  }  /*if (capi_season_tmp == NULL) ... else of season*/
  /* End of cleaning variable season */
  if((PyObject *)capi_rw_tmp!=rw_capi) {
    Py_XDECREF(capi_rw_tmp); }
  }  /*if (capi_rw_tmp == NULL) ... else of rw*/
  /* End of cleaning variable rw */
  } /*CHECKSCALAR(len(y)>=n)*/
  } /*if (f2py_success) of n*/
  /* End of cleaning variable n */
  } /*if (f2py_success) of no*/
  /* End of cleaning variable no */
  } /*if (f2py_success) of robust*/
  /* End of cleaning variable robust */
  } /*if (f2py_success) of itdeg*/
  /* End of cleaning variable itdeg */
  } /*if (f2py_success) of isdeg*/
  /* End of cleaning variable isdeg */
  } /*if (f2py_success) of ns*/
  /* End of cleaning variable ns */
  } /*if (f2py_success) of np*/
  /* End of cleaning variable np */
  if((PyObject *)capi_y_tmp!=y_capi) {
    Py_XDECREF(capi_y_tmp); }
  }  /*if (capi_y_tmp == NULL) ... else of y*/
  /* End of cleaning variable y */
/*end of cleanupfrompyobj*/
  if (capi_buildvalue == NULL) {
/*routdebugfailure*/
  } else {
/*routdebugleave*/
  }
  CFUNCSMESS("Freeing memory.\n");
/*freemem*/
#ifdef F2PY_REPORT_ATEXIT
f2py_stop_clock();
#endif
  return capi_buildvalue;
}
/******************************** end of stlez ********************************/

/*********************************** psort ***********************************/
static char doc_f2py_rout__stl_psort[] = "\
psort(a,ind,[n,ni])\n\nWrapper for ``psort``.\
\n\nParameters\n----------\n"
"a : input rank-1 array('d') with bounds (n)\n"
"ind : input rank-1 array('i') with bounds (ni)\n"
"\nOther Parameters\n----------------\n"
"n : input int, optional\n    Default: len(a)\n"
"ni : input int, optional\n    Default: len(ind)";
/* extern void F_FUNC(psort,PSORT)(double*,int*,int*,int*); */
static PyObject *f2py_rout__stl_psort(const PyObject *capi_self,
                           PyObject *capi_args,
                           PyObject *capi_keywds,
                           void (*f2py_func)(double*,int*,int*,int*)) {
  PyObject * volatile capi_buildvalue = NULL;
  volatile int f2py_success = 1;
/*decl*/

  double *a = NULL;
  npy_intp a_Dims[1] = {-1};
  const int a_Rank = 1;
  PyArrayObject *capi_a_tmp = NULL;
  int capi_a_intent = 0;
  PyObject *a_capi = Py_None;
  int n = 0;
  PyObject *n_capi = Py_None;
  int *ind = NULL;
  npy_intp ind_Dims[1] = {-1};
  const int ind_Rank = 1;
  PyArrayObject *capi_ind_tmp = NULL;
  int capi_ind_intent = 0;
  PyObject *ind_capi = Py_None;
  int ni = 0;
  PyObject *ni_capi = Py_None;
  static char *capi_kwlist[] = {"a","ind","n","ni",NULL};

/*routdebugenter*/
#ifdef F2PY_REPORT_ATEXIT
f2py_start_clock();
#endif
  if (!PyArg_ParseTupleAndKeywords(capi_args,capi_keywds,\
    "OO|OO:_stl.psort",\
    capi_kwlist,&a_capi,&ind_capi,&n_capi,&ni_capi))
    return NULL;
/*frompyobj*/
  /* Processing variable a */
  ;
  capi_a_intent |= F2PY_INTENT_IN;
  capi_a_tmp = array_from_pyobj(NPY_DOUBLE,a_Dims,a_Rank,capi_a_intent,a_capi);
  if (capi_a_tmp == NULL) {
    if (!PyErr_Occurred())
      PyErr_SetString(_stl_error,"failed in converting 1st argument `a' of _stl.psort to C/Fortran array" );
  } else {
    a = (double *)(PyArray_DATA(capi_a_tmp));

  /* Processing variable ind */
  ;
  capi_ind_intent |= F2PY_INTENT_IN;
  capi_ind_tmp = array_from_pyobj(NPY_INT,ind_Dims,ind_Rank,capi_ind_intent,ind_capi);
  if (capi_ind_tmp == NULL) {
    if (!PyErr_Occurred())
      PyErr_SetString(_stl_error,"failed in converting 2nd argument `ind' of _stl.psort to C/Fortran array" );
  } else {
    ind = (int *)(PyArray_DATA(capi_ind_tmp));

  /* Processing variable n */
  if (n_capi == Py_None) n = len(a); else
    f2py_success = int_from_pyobj(&n,n_capi,"_stl.psort() 1st keyword (n) can't be converted to int");
  if (f2py_success) {
  CHECKSCALAR(len(a)>=n,"len(a)>=n","1st keyword n","psort:n=%d",n) {
  /* Processing variable ni */
  if (ni_capi == Py_None) ni = len(ind); else
    f2py_success = int_from_pyobj(&ni,ni_capi,"_stl.psort() 2nd keyword (ni) can't be converted to int");
  if (f2py_success) {
  CHECKSCALAR(len(ind)>=ni,"len(ind)>=ni","2nd keyword ni","psort:ni=%d",ni) {
/*end of frompyobj*/
#ifdef F2PY_REPORT_ATEXIT
f2py_start_call_clock();
#endif
/*callfortranroutine*/
        (*f2py_func)(a,&n,ind,&ni);
if (PyErr_Occurred())
  f2py_success = 0;
#ifdef F2PY_REPORT_ATEXIT
f2py_stop_call_clock();
#endif
/*end of callfortranroutine*/
    if (f2py_success) {
/*pyobjfrom*/
/*end of pyobjfrom*/
    CFUNCSMESS("Building return value.\n");
    capi_buildvalue = Py_BuildValue("");
/*closepyobjfrom*/
/*end of closepyobjfrom*/
    } /*if (f2py_success) after callfortranroutine*/
/*cleanupfrompyobj*/
  } /*CHECKSCALAR(len(ind)>=ni)*/
  } /*if (f2py_success) of ni*/
  /* End of cleaning variable ni */
  } /*CHECKSCALAR(len(a)>=n)*/
  } /*if (f2py_success) of n*/
  /* End of cleaning variable n */
  if((PyObject *)capi_ind_tmp!=ind_capi) {
    Py_XDECREF(capi_ind_tmp); }
  }  /*if (capi_ind_tmp == NULL) ... else of ind*/
  /* End of cleaning variable ind */
  if((PyObject *)capi_a_tmp!=a_capi) {
    Py_XDECREF(capi_a_tmp); }
  }  /*if (capi_a_tmp == NULL) ... else of a*/
  /* End of cleaning variable a */
/*end of cleanupfrompyobj*/
  if (capi_buildvalue == NULL) {
/*routdebugfailure*/
  } else {
/*routdebugleave*/
  }
  CFUNCSMESS("Freeing memory.\n");
/*freemem*/
#ifdef F2PY_REPORT_ATEXIT
f2py_stop_clock();
#endif
  return capi_buildvalue;
}
/******************************** end of psort ********************************/
/*eof body*/

/******************* See f2py2e/f90mod_rules.py: buildhooks *******************/
/*need_f90modhooks*/

/************** See f2py2e/rules.py: module_rules['modulebody'] **************/

/******************* See f2py2e/common_rules.py: buildhooks *******************/

/*need_commonhooks*/

/**************************** See f2py2e/rules.py ****************************/

static FortranDataDef f2py_routine_defs[] = {
  {"stl",-1,{{-1}},0,(char *)F_FUNC(stl,STL),(f2py_init_func)f2py_rout__stl_stl,doc_f2py_rout__stl_stl},
  {"ess",-1,{{-1}},0,(char *)F_FUNC(ess,ESS),(f2py_init_func)f2py_rout__stl_ess,doc_f2py_rout__stl_ess},
  {"est",-1,{{-1}},0,(char *)F_FUNC(est,EST),(f2py_init_func)f2py_rout__stl_est,doc_f2py_rout__stl_est},
  {"fts",-1,{{-1}},0,(char *)F_FUNC(fts,FTS),(f2py_init_func)f2py_rout__stl_fts,doc_f2py_rout__stl_fts},
  {"ma",-1,{{-1}},0,(char *)F_FUNC(ma,MA),(f2py_init_func)f2py_rout__stl_ma,doc_f2py_rout__stl_ma},
  {"onestp",-1,{{-1}},0,(char *)F_FUNC(onestp,ONESTP),(f2py_init_func)f2py_rout__stl_onestp,doc_f2py_rout__stl_onestp},
  {"rwts",-1,{{-1}},0,(char *)F_FUNC(rwts,RWTS),(f2py_init_func)f2py_rout__stl_rwts,doc_f2py_rout__stl_rwts},
  {"ss",-1,{{-1}},0,(char *)F_FUNC(ss,SS),(f2py_init_func)f2py_rout__stl_ss,doc_f2py_rout__stl_ss},
  {"stlez",-1,{{-1}},0,(char *)F_FUNC(stlez,STLEZ),(f2py_init_func)f2py_rout__stl_stlez,doc_f2py_rout__stl_stlez},
  {"psort",-1,{{-1}},0,(char *)F_FUNC(psort,PSORT),(f2py_init_func)f2py_rout__stl_psort,doc_f2py_rout__stl_psort},

/*eof routine_defs*/
  {NULL}
};

static PyMethodDef f2py_module_methods[] = {

  {NULL,NULL}
};

#if PY_VERSION_HEX >= 0x03000000
static struct PyModuleDef moduledef = {
  PyModuleDef_HEAD_INIT,
  "_stl",
  NULL,
  -1,
  f2py_module_methods,
  NULL,
  NULL,
  NULL,
  NULL
};
#endif

#if PY_VERSION_HEX >= 0x03000000
#define RETVAL m
PyMODINIT_FUNC PyInit__stl(void) {
#else
#define RETVAL
PyMODINIT_FUNC init_stl(void) {
#endif
  int i;
  PyObject *m,*d, *s, *tmp;
#if PY_VERSION_HEX >= 0x03000000
  m = _stl_module = PyModule_Create(&moduledef);
#else
  m = _stl_module = Py_InitModule("_stl", f2py_module_methods);
#endif
  Py_TYPE(&PyFortran_Type) = &PyType_Type;
  import_array();
  if (PyErr_Occurred())
    {PyErr_SetString(PyExc_ImportError, "can't initialize module _stl (failed to import numpy)"); return RETVAL;}
  d = PyModule_GetDict(m);
  s = PyString_FromString("$Revision: $");
  PyDict_SetItemString(d, "__version__", s);
  Py_DECREF(s);
#if PY_VERSION_HEX >= 0x03000000
  s = PyUnicode_FromString(
#else
  s = PyString_FromString(
#endif
    "This module '_stl' is auto-generated with f2py (version:2).\nFunctions:\n"
"  rw,season,trend,work = stl(y,np,ns,nt,nl,isdeg,itdeg,ildeg,nsjump,ntjump,nljump,ni,no,n=len(y))\n"
"  ess(y,len_bn,ideg,njump,userw,rw,ys,res,n=len(y))\n"
"  est(y,len_bn,ideg,xs,ys,nleft,nright,w,userw,rw,ok,n=len(y))\n"
"  fts(x,np,trend,work,n=len(x))\n"
"  ma(x,len_bn,ave,n=len(x))\n"
"  rw,season,trend,work = onestp(y,np,ns,nt,nl,isdeg,itdeg,ildeg,nsjump,ntjump,nljump,ni,userw,n=len(y))\n"
"  rwts(y,fit,rw,n=len(y))\n"
"  ss(y,np,ns,isdeg,nsjump,userw,rw,season,work1,work2,work3,work4,n=len(y))\n"
"  stlez(y,np,ns,isdeg,itdeg,robust,no,rw,season,trend,work,n=len(y))\n"
"  psort(a,ind,n=len(a),ni=len(ind))\n"
".");
  PyDict_SetItemString(d, "__doc__", s);
  Py_DECREF(s);
  _stl_error = PyErr_NewException ("_stl.error", NULL, NULL);
  /*
   * Store the error object inside the dict, so that it could get deallocated.
   * (in practice, this is a module, so it likely will not and cannot.)
   */
  PyDict_SetItemString(d, "__stl_error", _stl_error);
  Py_DECREF(_stl_error);
  for(i=0;f2py_routine_defs[i].name!=NULL;i++) {
    tmp = PyFortranObject_NewAsAttr(&f2py_routine_defs[i]);
    PyDict_SetItemString(d, f2py_routine_defs[i].name, tmp);
    Py_DECREF(tmp);
  }










/*eof initf2pywraphooks*/
/*eof initf90modhooks*/

/*eof initcommonhooks*/


#ifdef F2PY_REPORT_ATEXIT
  if (! PyErr_Occurred())
    on_exit(f2py_report_on_exit,(void*)"_stl");
#endif
  return RETVAL;
}
#ifdef __cplusplus
}
#endif
